Add workouts 13-28 for Spreadsheets
enkidevs/curriculum pull request #2312
Opened 2020-08-19 14:44 UTC by Stefan-Stojanovic

2020-08-19 14:45 UTC, enki-hq commented
Failed parsing files: 
  - spreadsheets/intermediate/functions-and-formulas-iii/concat.md: 
 > 	No valid answer list in question node
  - spreadsheets/intermediate/functions-and-formulas-iii/proper.md: 
 > 	No valid answer list in question node
  - spreadsheets/intermediate/google-functions/detectlanguage.md: 
 > 	Cannot compile node with invalid type heading
  - spreadsheets/intermediate/pivot-tables-ii/how-to-extract-a-table-from-a-pivot-table.md: 
 > 	Missing compiler for node of type `questionGap`: `[object Object]`

2020-08-19 14:47 UTC, enki-hq commented
Failed parsing files: 
  - spreadsheets/intermediate/functions-and-formulas-iii/concat.md: 
 > 	No valid answer list in question node
  - spreadsheets/intermediate/functions-and-formulas-iii/proper.md: 
 > 	No valid answer list in question node
  - spreadsheets/intermediate/google-functions/detectlanguage.md: 
 > 	Cannot compile node with invalid type heading
  - spreadsheets/intermediate/pivot-tables-ii/how-to-extract-a-table-from-a-pivot-table.md: 
 > 	Missing compiler for node of type `questionGap`: `[object Object]`

2020-08-19 14:49 UTC, enki-hq commented
Failed parsing files: 
  - spreadsheets/intermediate/functions-and-formulas-iii/proper.md: 
 > 	No valid answer list in question node
  - spreadsheets/intermediate/google-functions/detectlanguage.md: 
 > 	Cannot compile node with invalid type heading
  - spreadsheets/intermediate/pivot-tables-ii/how-to-extract-a-table-from-a-pivot-table.md: 
 > 	Missing compiler for node of type `questionGap`: `[object Object]`

2020-08-19 14:49 UTC, enki-hq commented
Failed parsing files: 
  - spreadsheets/intermediate/google-functions/detectlanguage.md: 
 > 	Cannot compile node with invalid type heading
  - spreadsheets/intermediate/pivot-tables-ii/how-to-extract-a-table-from-a-pivot-table.md: 
 > 	Missing compiler for node of type `questionGap`: `[object Object]`

2020-08-19 14:50 UTC, enki-hq commented
Failed parsing files: 
  - spreadsheets/intermediate/pivot-tables-ii/how-to-extract-a-table-from-a-pivot-table.md: 
 > 	Missing compiler for node of type `questionGap`: `[object Object]`

2020-08-19 14:52 UTC, enki-hq commented
Failed parsing files: 
  - glossary/general/spreadsheets/divide-by-zero-error.md: 
 > 	Cannot compile node with invalid type paragraph
  - glossary/general/spreadsheets/name-error.md: 
 > 	Cannot compile node with invalid type paragraph
  - glossary/general/spreadsheets/not-available-error.md: 
 > 	Cannot compile node with invalid type paragraph
  - glossary/general/spreadsheets/reference-error.md: 
 > 	Cannot compile node with invalid type paragraph
  - glossary/general/spreadsheets/value-error.md: 
 > 	Cannot compile node with invalid type paragraph
  - glossary/general/spreadsheets/divide-by-zero-error.md: 
 > 	Cannot compile node with invalid type paragraph
  - glossary/general/spreadsheets/name-error.md: 
 > 	Cannot compile node with invalid type paragraph
  - glossary/general/spreadsheets/not-available-error.md: 
 > 	Cannot compile node with invalid type paragraph
  - glossary/general/spreadsheets/reference-error.md: 
 > 	Cannot compile node with invalid type paragraph
  - glossary/general/spreadsheets/value-error.md: 
 > 	Cannot compile node with invalid type paragraph

2020-08-19 15:11 UTC, enki-hq commented
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| what-are-pivot-tables  | Insight slug `what-are-pivot-tables ` contains forbidden characters. |
| series | No footnote matches found in content. |
| equals-and-eq | No matching footnotes found. |
| greater-than-gt-greater-than-or-equal-gte | No footnote matches found in content. |
| ifna | No matching glossary entry found in the database or this pull request. |
| ifs | No matching glossary entry found in the database or this pull request. |
| min-max-average | No matching glossary entry found in the database or this pull request. |
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| comparison-operator-and-functions | One of the mentioned insights couldn't be found in this pull request or the database. |
| intro-to-pivot-tables | One of the mentioned insights couldn't be found in this pull request or the database. |
| parser-functions | One of the mentioned insights couldn't be found in this pull request or the database. |
| chart-customization | One of the mentioned insights couldn't be found in this pull request or the database. |
| pivot-tables-ii | One of the mentioned insights couldn't be found in this pull request or the database. |
| charts-2 | One of the mentioned insights couldn't be found in this pull request or the database. |
| sparklline-function | One of the mentioned insights couldn't be found in this pull request or the database. |
| useful-functions-and-formulas | One of the mentioned insights couldn't be found in this pull request or the database. |
### Course

| Course Name | Error Message |
|:-:|:-:|
| intermediate | We couldn't find these workouts: `functions-and-formlas-iii`, `import-functions`, `sparkline-functions`, `comparison-operators-and-functions`. |
### Title

| File Name | Error Message |
|:-:|:-:|
| add-ons | Workout title should be `` Add-Ons `` |
| chart-customization | Workout title should be `` Charts Ii `` |
| charts-2 | Workout title should be `` Charts Ii `` |
| conditional-formatting | Workout title should be `` Conditional Formatting `` |
| functions-and-formulas-iii | Workout title should be `` Functions & Formulas Iii `` |
| logical-functions-ii | Workout title should be `` Logical Functions Ii `` |
| pivot-tables-ii | Workout title should be `` Pivot Tables Ii `` |
| useful-functions-and-formulas | Workout title should be `` Functions & Formulas Ii `` |
| how-to-install-an-add-on | Insight title should be `` How to Install an Add-On `` |
| how-to-manage-add-ons | Insight title should be `` Managing Add-Ons `` |
| useful-add-ons-ii | Insight title should be `` Useful Add-Ons Continued `` |
| useful-add-ons | Insight title should be `` Useful Add-Ons `` |
| what-are-add-ons | Insight title should be `` What Are Add-Ons `` |
| equals-and-eq | Insight title should be `` `=` and `Eq()` `` |
| greater-than-gt-greater-than-or-equal-gte | Insight title should be `` `>`, `>=`, `Gt()` & `Gte()` `` |
| less-than-lt-less-than-or-equal-lte | Insight title should be `` `<`, `<=`, `Lt()` & `Lte()` `` |
| not-equal-ne | Insight title should be `` `<>` & `Ne()` `` |
| concat | Insight title should be `` Concat `` |
| concatenate | Insight title should be `` Concatenate `` |
| proper | Insight title should be `` Proper `` |
| unique | Insight title should be `` Unique `` |
| detectlanguage | Insight title should be `` Detectlanguage `` |
| google-image | Insight title should be `` Image `` |
| googletranslate | Insight title should be `` Googletranslate `` |
| importfeed-options-and-example | Insight title should be `` =Importfeed() options & Example `` |
| importfeed | Insight title should be `` =Importfeed() `` |
| importhtml | Insight title should be `` =Importhtml() `` |
| importrange-example | Insight title should be `` =Importrange() example `` |
| importrange | Insight title should be `` =Importrange() `` |
| importxml | Insight title should be `` Importxml `` |
| iferror | Insight title should be `` Iferror `` |
| ifna | Insight title should be `` Ifna `` |
| ifs | Insight title should be `` Ifs `` |
| switch | Insight title should be `` Switch `` |
| xor | Insight title should be `` Xor `` |
| ceiling-function | Insight title should be `` Ceiling `` |
| countunique-function | Insight title should be `` Countunique `` |
| even-odd-iseven-isodd | Insight title should be `` Even, Odd, Iseven & Isodd `` |
| floor-function | Insight title should be `` Floor `` |
| power-function | Insight title should be `` The Power Function `` |
| to-date | Insight title should be `` To_date `` |
| to-dollars | Insight title should be `` To_dollars `` |
| to-percent | Insight title should be `` To_percent `` |
| to-pure-number | Insight title should be `` To_pure_number `` |
| to-text | Insight title should be `` To_text `` |
| how-to-extract-a-table-from-a-pivot-table | Insight title should be `` How to Extract a Table from a Pivot Table `` |
| multiple-calculations | Insight title should be `` Multiple Calculations `` |
| how-to-create-a-sparkline-chart | Insight title should be `` How to Create a Sparkline Chart? `` |
| averageif-countif | Insight title should be `` Averageif, Countif `` |
| min-max-average | Insight title should be `` `Min`, `Max`, `Average` `` |
| split | Insight title should be `` Split `` |
| spreadsheets/divide-by-zero-error.md | Glossary title should be `` Divide by Zero Error `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-08-19 15:47 UTC, enki-hq commented
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| ifna | No matching glossary entry found in the database or this pull request. |
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| functions-and-formulas-ii | One of the mentioned insights couldn't be found in this pull request or the database. |
| pivot-tables-ii | One of the mentioned insights couldn't be found in this pull request or the database. |
| sparklline-function | One of the mentioned insights couldn't be found in this pull request or the database. |
### Course

| Course Name | Error Message |
|:-:|:-:|
| intermediate | We couldn't find these workouts: `useful-functions-and-formulas`, `sparkline-function`. |
### Title

| File Name | Error Message |
|:-:|:-:|
| charts-2 | Workout title should be `` Charts Ii `` |
| functions-and-formulas-ii | Workout title should be `` Functions & Formulas Ii `` |
| functions-and-formulas-iii | Workout title should be `` Functions & Formulas Iii `` |
| logical-functions-ii | Workout title should be `` Logical Functions Ii `` |
| pivot-tables-ii | Workout title should be `` Pivot Tables Ii `` |
| how-to-install-an-add-on | Insight title should be `` How to Install an Add-On `` |
| how-to-manage-add-ons | Insight title should be `` Managing Add-Ons `` |
| useful-add-ons-ii | Insight title should be `` Useful Add-Ons Continued `` |
| useful-add-ons | Insight title should be `` Useful Add-Ons `` |
| what-are-add-ons | Insight title should be `` What Are Add-Ons `` |
| equals-and-eq | Insight title should be `` `=` and `Eq()` `` |
| greater-than-gt-greater-than-or-equal-gte | Insight title should be `` `>`, `>=`, `Gt()` & `Gte()` `` |
| less-than-lt-less-than-or-equal-lte | Insight title should be `` `<`, `<=`, `Lt()` & `Lte()` `` |
| not-equal-and-ne | Insight title should be `` `<>` & `Ne()` `` |
| averageif-countif | Insight title should be `` Averageif, Countif `` |
| min-max-average | Insight title should be `` `Min`, `Max`, `Average` `` |
| split | Insight title should be `` Split `` |
| concat | Insight title should be `` Concat `` |
| concatenate | Insight title should be `` Concatenate `` |
| proper | Insight title should be `` Proper `` |
| unique | Insight title should be `` Unique `` |
| detectlanguage | Insight title should be `` Detectlanguage `` |
| google-image | Insight title should be `` Image `` |
| googletranslate | Insight title should be `` Googletranslate `` |
| importfeed-options-and-example | Insight title should be `` =Importfeed() options & Example `` |
| importfeed | Insight title should be `` =Importfeed() `` |
| importhtml | Insight title should be `` =Importhtml() `` |
| importrange-example | Insight title should be `` =Importrange() example `` |
| importrange | Insight title should be `` =Importrange() `` |
| importxml | Insight title should be `` Importxml `` |
| iferror | Insight title should be `` Iferror `` |
| ifna | Insight title should be `` Ifna `` |
| ifs | Insight title should be `` Ifs `` |
| switch | Insight title should be `` Switch `` |
| xor | Insight title should be `` Xor `` |
| ceiling-function | Insight title should be `` Ceiling `` |
| countunique-function | Insight title should be `` Countunique `` |
| even-odd-iseven-isodd | Insight title should be `` Even, Odd, Iseven & Isodd `` |
| floor-function | Insight title should be `` Floor `` |
| power-function | Insight title should be `` The Power Function `` |
| to-date | Insight title should be `` To_date `` |
| to-dollars | Insight title should be `` To_dollars `` |
| to-percent | Insight title should be `` To_percent `` |
| to-pure-number | Insight title should be `` To_pure_number `` |
| to-text | Insight title should be `` To_text `` |
| how-to-extract-a-table-from-a-pivot-table | Insight title should be `` How to Extract a Table from a Pivot Table `` |
| multiple-calculations | Insight title should be `` Multiple Calculations `` |
| how-to-create-a-sparkline-chart | Insight title should be `` How to Create a Sparkline Chart? `` |
| spreadsheets/divide-by-zero-error.md | Glossary title should be `` Divide by Zero Error `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-08-19 15:49 UTC, enki-hq commented
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| ifna | No matching glossary entry found in the database or this pull request. |
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| functions-and-formulas-ii | One of the mentioned insights couldn't be found in this pull request or the database. |
| pivot-tables-ii | One of the mentioned insights couldn't be found in this pull request or the database. |
| sparklline-function | One of the mentioned insights couldn't be found in this pull request or the database. |
### Course

| Course Name | Error Message |
|:-:|:-:|
| intermediate | We couldn't find these workouts: `useful-functions-and-formulas`, `sparkline-function`. |
### Title

| File Name | Error Message |
|:-:|:-:|
| charts-2 | Workout title should be `` Charts Ii `` |
| functions-and-formulas-ii | Workout title should be `` Functions & Formulas Ii `` |
| functions-and-formulas-iii | Workout title should be `` Functions & Formulas Iii `` |
| logical-functions-ii | Workout title should be `` Logical Functions Ii `` |
| pivot-tables-ii | Workout title should be `` Pivot Tables Ii `` |
| how-to-install-an-add-on | Insight title should be `` How to Install an Add-On `` |
| how-to-manage-add-ons | Insight title should be `` Managing Add-Ons `` |
| useful-add-ons-ii | Insight title should be `` Useful Add-Ons Continued `` |
| useful-add-ons | Insight title should be `` Useful Add-Ons `` |
| what-are-add-ons | Insight title should be `` What Are Add-Ons `` |
| equals-and-eq | Insight title should be `` `=` and `Eq()` `` |
| greater-than-gt-greater-than-or-equal-gte | Insight title should be `` `>`, `>=`, `Gt()` & `Gte()` `` |
| less-than-lt-less-than-or-equal-lte | Insight title should be `` `<`, `<=`, `Lt()` & `Lte()` `` |
| not-equal-and-ne | Insight title should be `` `<>` & `Ne()` `` |
| averageif-countif | Insight title should be `` Averageif, Countif `` |
| min-max-average | Insight title should be `` `Min`, `Max`, `Average` `` |
| split | Insight title should be `` Split `` |
| concat | Insight title should be `` Concat `` |
| concatenate | Insight title should be `` Concatenate `` |
| proper | Insight title should be `` Proper `` |
| unique | Insight title should be `` Unique `` |
| detectlanguage | Insight title should be `` Detectlanguage `` |
| google-image | Insight title should be `` Image `` |
| googletranslate | Insight title should be `` Googletranslate `` |
| importfeed-options-and-example | Insight title should be `` =Importfeed() options & Example `` |
| importfeed | Insight title should be `` =Importfeed() `` |
| importhtml | Insight title should be `` =Importhtml() `` |
| importrange-example | Insight title should be `` =Importrange() example `` |
| importrange | Insight title should be `` =Importrange() `` |
| importxml | Insight title should be `` Importxml `` |
| iferror | Insight title should be `` Iferror `` |
| ifna | Insight title should be `` Ifna `` |
| ifs | Insight title should be `` Ifs `` |
| switch | Insight title should be `` Switch `` |
| xor | Insight title should be `` Xor `` |
| ceiling-function | Insight title should be `` Ceiling `` |
| countunique-function | Insight title should be `` Countunique `` |
| even-odd-iseven-isodd | Insight title should be `` Even, Odd, Iseven & Isodd `` |
| floor-function | Insight title should be `` Floor `` |
| power-function | Insight title should be `` The Power Function `` |
| to-date | Insight title should be `` To_date `` |
| to-dollars | Insight title should be `` To_dollars `` |
| to-percent | Insight title should be `` To_percent `` |
| to-pure-number | Insight title should be `` To_pure_number `` |
| to-text | Insight title should be `` To_text `` |
| how-to-extract-a-table-from-a-pivot-table | Insight title should be `` How to Extract a Table from a Pivot Table `` |
| multiple-calculations | Insight title should be `` Multiple Calculations `` |
| how-to-create-a-sparkline-chart | Insight title should be `` How to Create a Sparkline Chart? `` |
| spreadsheets/divide-by-zero-error.md | Glossary title should be `` Divide by Zero Error `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-08-19 15:52 UTC, enki-hq commented
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| ifna | No matching glossary entry found in the database or this pull request. |
### Title

| File Name | Error Message |
|:-:|:-:|
| charts-2 | Workout title should be `` Charts Ii `` |
| functions-and-formulas-ii | Workout title should be `` Functions & Formulas Ii `` |
| functions-and-formulas-iii | Workout title should be `` Functions & Formulas Iii `` |
| logical-functions-ii | Workout title should be `` Logical Functions Ii `` |
| pivot-tables-ii | Workout title should be `` Pivot Tables Ii `` |
| how-to-install-an-add-on | Insight title should be `` How to Install an Add-On `` |
| how-to-manage-add-ons | Insight title should be `` Managing Add-Ons `` |
| useful-add-ons-ii | Insight title should be `` Useful Add-Ons Continued `` |
| useful-add-ons | Insight title should be `` Useful Add-Ons `` |
| what-are-add-ons | Insight title should be `` What Are Add-Ons `` |
| equals-and-eq | Insight title should be `` `=` and `Eq()` `` |
| greater-than-gt-greater-than-or-equal-gte | Insight title should be `` `>`, `>=`, `Gt()` & `Gte()` `` |
| less-than-lt-less-than-or-equal-lte | Insight title should be `` `<`, `<=`, `Lt()` & `Lte()` `` |
| not-equal-and-ne | Insight title should be `` `<>` & `Ne()` `` |
| averageif-countif | Insight title should be `` Averageif, Countif `` |
| min-max-average | Insight title should be `` `Min`, `Max`, `Average` `` |
| split | Insight title should be `` Split `` |
| concat | Insight title should be `` Concat `` |
| concatenate | Insight title should be `` Concatenate `` |
| proper | Insight title should be `` Proper `` |
| unique | Insight title should be `` Unique `` |
| detectlanguage | Insight title should be `` Detectlanguage `` |
| google-image | Insight title should be `` Image `` |
| googletranslate | Insight title should be `` Googletranslate `` |
| importfeed-options-and-example | Insight title should be `` =Importfeed() options & Example `` |
| importfeed | Insight title should be `` =Importfeed() `` |
| importhtml | Insight title should be `` =Importhtml() `` |
| importrange-example | Insight title should be `` =Importrange() example `` |
| importrange | Insight title should be `` =Importrange() `` |
| importxml | Insight title should be `` Importxml `` |
| iferror | Insight title should be `` Iferror `` |
| ifna | Insight title should be `` Ifna `` |
| ifs | Insight title should be `` Ifs `` |
| switch | Insight title should be `` Switch `` |
| xor | Insight title should be `` Xor `` |
| ceiling-function | Insight title should be `` Ceiling `` |
| countunique-function | Insight title should be `` Countunique `` |
| even-odd-iseven-isodd | Insight title should be `` Even, Odd, Iseven & Isodd `` |
| floor-function | Insight title should be `` Floor `` |
| power-function | Insight title should be `` The Power Function `` |
| to-date | Insight title should be `` To_date `` |
| to-dollars | Insight title should be `` To_dollars `` |
| to-percent | Insight title should be `` To_percent `` |
| to-pure-number | Insight title should be `` To_pure_number `` |
| to-text | Insight title should be `` To_text `` |
| how-to-extract-a-table-from-a-pivot-table | Insight title should be `` How to Extract a Table from a Pivot Table `` |
| multiple-calculations | Insight title should be `` Multiple Calculations `` |
| how-to-create-a-sparkline-chart | Insight title should be `` How to Create a Sparkline Chart? `` |
| spreadsheets/divide-by-zero-error.md | Glossary title should be `` Divide by Zero Error `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-08-19 16:05 UTC, enki-hq commented
### Title

| File Name | Error Message |
|:-:|:-:|
| charts-2 | Workout title should be `` Charts Ii `` |
| functions-and-formulas-ii | Workout title should be `` Functions & Formulas Ii `` |
| functions-and-formulas-iii | Workout title should be `` Functions & Formulas Iii `` |
| logical-functions-ii | Workout title should be `` Logical Functions Ii `` |
| pivot-tables-ii | Workout title should be `` Pivot Tables Ii `` |
| how-to-install-an-add-on | Insight title should be `` How to Install an Add-On `` |
| how-to-manage-add-ons | Insight title should be `` Managing Add-Ons `` |
| useful-add-ons-ii | Insight title should be `` Useful Add-Ons Continued `` |
| useful-add-ons | Insight title should be `` Useful Add-Ons `` |
| what-are-add-ons | Insight title should be `` What Are Add-Ons `` |
| equals-and-eq | Insight title should be `` `=` and `Eq()` `` |
| greater-than-gt-greater-than-or-equal-gte | Insight title should be `` `>`, `>=`, `Gt()` & `Gte()` `` |
| less-than-lt-less-than-or-equal-lte | Insight title should be `` `<`, `<=`, `Lt()` & `Lte()` `` |
| not-equal-and-ne | Insight title should be `` `<>` & `Ne()` `` |
| averageif-countif | Insight title should be `` Averageif, Countif `` |
| min-max-average | Insight title should be `` `Min`, `Max`, `Average` `` |
| split | Insight title should be `` Split `` |
| concat | Insight title should be `` Concat `` |
| concatenate | Insight title should be `` Concatenate `` |
| proper | Insight title should be `` Proper `` |
| unique | Insight title should be `` Unique `` |
| detectlanguage | Insight title should be `` Detectlanguage `` |
| google-image | Insight title should be `` Image `` |
| googletranslate | Insight title should be `` Googletranslate `` |
| importfeed-options-and-example | Insight title should be `` =Importfeed() options & Example `` |
| importfeed | Insight title should be `` =Importfeed() `` |
| importhtml | Insight title should be `` =Importhtml() `` |
| importrange-example | Insight title should be `` =Importrange() example `` |
| importrange | Insight title should be `` =Importrange() `` |
| importxml | Insight title should be `` Importxml `` |
| iferror | Insight title should be `` Iferror `` |
| ifna | Insight title should be `` Ifna `` |
| ifs | Insight title should be `` Ifs `` |
| switch | Insight title should be `` Switch `` |
| xor | Insight title should be `` Xor `` |
| ceiling-function | Insight title should be `` Ceiling `` |
| countunique-function | Insight title should be `` Countunique `` |
| even-odd-iseven-isodd | Insight title should be `` Even, Odd, Iseven & Isodd `` |
| floor-function | Insight title should be `` Floor `` |
| power-function | Insight title should be `` The Power Function `` |
| to-date | Insight title should be `` To_date `` |
| to-dollars | Insight title should be `` To_dollars `` |
| to-percent | Insight title should be `` To_percent `` |
| to-pure-number | Insight title should be `` To_pure_number `` |
| to-text | Insight title should be `` To_text `` |
| how-to-extract-a-table-from-a-pivot-table | Insight title should be `` How to Extract a Table from a Pivot Table `` |
| multiple-calculations | Insight title should be `` Multiple Calculations `` |
| how-to-create-a-sparkline-chart | Insight title should be `` How to Create a Sparkline Chart? `` |
| spreadsheets/divide-by-zero-error.md | Glossary title should be `` Divide by Zero Error `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-08-19 16:11 UTC, enki-hq commented
### Title

| File Name | Error Message |
|:-:|:-:|
| charts-2 | Workout title should be `` Charts Ii `` |
| functions-and-formulas-ii | Workout title should be `` Functions & Formulas Ii `` |
| functions-and-formulas-iii | Workout title should be `` Functions & Formulas Iii `` |
| logical-functions-ii | Workout title should be `` Logical Functions Ii `` |
| pivot-tables-ii | Workout title should be `` Pivot Tables Ii `` |
| equals-and-eq | Insight title should be `` `=` and `Eq()` `` |
| greater-than-gt-greater-than-or-equal-gte | Insight title should be `` `>`, `>=`, `Gt()` & `Gte()` `` |
| less-than-lt-less-than-or-equal-lte | Insight title should be `` `<`, `<=`, `Lt()` & `Lte()` `` |
| not-equal-and-ne | Insight title should be `` `<>` & `Ne()` `` |
| averageif-countif | Insight title should be `` Averageif, Countif `` |
| min-max-average | Insight title should be `` `Min`, `Max`, `Average` `` |
| split | Insight title should be `` Split `` |
| concat | Insight title should be `` Concat `` |
| concatenate | Insight title should be `` Concatenate `` |
| proper | Insight title should be `` Proper `` |
| unique | Insight title should be `` Unique `` |
| detectlanguage | Insight title should be `` Detectlanguage `` |
| google-image | Insight title should be `` Image `` |
| googletranslate | Insight title should be `` Googletranslate `` |
| importfeed-options-and-example | Insight title should be `` =Importfeed() options & Example `` |
| importfeed | Insight title should be `` =Importfeed() `` |
| importhtml | Insight title should be `` =Importhtml() `` |
| importrange-example | Insight title should be `` =Importrange() example `` |
| importrange | Insight title should be `` =Importrange() `` |
| importxml | Insight title should be `` Importxml `` |
| iferror | Insight title should be `` Iferror `` |
| ifna | Insight title should be `` Ifna `` |
| ifs | Insight title should be `` Ifs `` |
| switch | Insight title should be `` Switch `` |
| xor | Insight title should be `` Xor `` |
| ceiling-function | Insight title should be `` Ceiling `` |
| countunique-function | Insight title should be `` Countunique `` |
| even-odd-iseven-isodd | Insight title should be `` Even, Odd, Iseven & Isodd `` |
| floor-function | Insight title should be `` Floor `` |
| power-function | Insight title should be `` The Power Function `` |
| to-date | Insight title should be `` To_date `` |
| to-dollars | Insight title should be `` To_dollars `` |
| to-percent | Insight title should be `` To_percent `` |
| to-pure-number | Insight title should be `` To_pure_number `` |
| to-text | Insight title should be `` To_text `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-08-20 13:36 UTC, enki-hq commented
### Title

| File Name | Error Message |
|:-:|:-:|
| charts-2 | Workout title should be `` Charts Ii `` |
| functions-and-formulas-ii | Workout title should be `` Functions & Formulas Ii `` |
| functions-and-formulas-iii | Workout title should be `` Functions & Formulas Iii `` |
| logical-functions-ii | Workout title should be `` Logical Functions Ii `` |
| pivot-tables-ii | Workout title should be `` Pivot Tables Ii `` |
| equals-and-eq | Insight title should be `` `=` and `Eq()` `` |
| greater-than-gt-greater-than-or-equal-gte | Insight title should be `` `>`, `>=`, `Gt()` & `Gte()` `` |
| less-than-lt-less-than-or-equal-lte | Insight title should be `` `<`, `<=`, `Lt()` & `Lte()` `` |
| not-equal-and-ne | Insight title should be `` `<>` & `Ne()` `` |
| averageif-countif | Insight title should be `` Averageif, Countif `` |
| min-max-average | Insight title should be `` `Min`, `Max`, `Average` `` |
| split | Insight title should be `` Split `` |
| concat | Insight title should be `` Concat `` |
| concatenate | Insight title should be `` Concatenate `` |
| proper | Insight title should be `` Proper `` |
| unique | Insight title should be `` Unique `` |
| detectlanguage | Insight title should be `` Detectlanguage `` |
| google-image | Insight title should be `` Image `` |
| googletranslate | Insight title should be `` Googletranslate `` |
| importfeed-options-and-example | Insight title should be `` =Importfeed() options & Example `` |
| importfeed | Insight title should be `` =Importfeed() `` |
| importhtml | Insight title should be `` =Importhtml() `` |
| importrange-example | Insight title should be `` =Importrange() example `` |
| importrange | Insight title should be `` =Importrange() `` |
| importxml | Insight title should be `` Importxml `` |
| iferror | Insight title should be `` Iferror `` |
| ifna | Insight title should be `` Ifna `` |
| ifs | Insight title should be `` Ifs `` |
| switch | Insight title should be `` Switch `` |
| xor | Insight title should be `` Xor `` |
| ceiling-function | Insight title should be `` Ceiling `` |
| countunique-function | Insight title should be `` Countunique `` |
| even-odd-iseven-isodd | Insight title should be `` Even, Odd, Iseven & Isodd `` |
| floor-function | Insight title should be `` Floor `` |
| power-function | Insight title should be `` The Power Function `` |
| to-date | Insight title should be `` To_date `` |
| to-dollars | Insight title should be `` To_dollars `` |
| to-percent | Insight title should be `` To_percent `` |
| to-pure-number | Insight title should be `` To_pure_number `` |
| to-text | Insight title should be `` To_text `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-08-20 16:03 UTC, enki-hq commented
### Title

| File Name | Error Message |
|:-:|:-:|
| charts-2 | Workout title should be `` Charts Ii `` |
| functions-and-formulas-ii | Workout title should be `` Functions & Formulas Ii `` |
| functions-and-formulas-iii | Workout title should be `` Functions & Formulas Iii `` |
| logical-functions-ii | Workout title should be `` Logical Functions Ii `` |
| pivot-tables-ii | Workout title should be `` Pivot Tables Ii `` |
| always-check-functions-names | Insight title should be `` Always Check Function Names `` |
| spreadsheet-pemdas | Insight title should be `` Order of Operations `` |
| equals-and-eq | Insight title should be `` `=` and `Eq()` `` |
| greater-than-gt-greater-than-or-equal-gte | Insight title should be `` `>`, `>=`, `Gt()` & `Gte()` `` |
| less-than-lt-less-than-or-equal-lte | Insight title should be `` `<`, `<=`, `Lt()` & `Lte()` `` |
| not-equal-and-ne | Insight title should be `` `<>` & `Ne()` `` |
| averageif-countif | Insight title should be `` Averageif, Countif `` |
| min-max-average | Insight title should be `` `Min`, `Max`, `Average` `` |
| split | Insight title should be `` Split `` |
| concat | Insight title should be `` Concat `` |
| concatenate | Insight title should be `` Concatenate `` |
| proper | Insight title should be `` Proper `` |
| unique | Insight title should be `` Unique `` |
| detectlanguage | Insight title should be `` Detectlanguage `` |
| google-image | Insight title should be `` Image `` |
| googletranslate | Insight title should be `` Googletranslate `` |
| importfeed-options-and-example | Insight title should be `` =Importfeed() options & Example `` |
| importfeed | Insight title should be `` =Importfeed() `` |
| importhtml | Insight title should be `` =Importhtml() `` |
| importrange-example | Insight title should be `` =Importrange() example `` |
| importrange | Insight title should be `` =Importrange() `` |
| importxml | Insight title should be `` Importxml `` |
| iferror | Insight title should be `` Iferror `` |
| ifna | Insight title should be `` Ifna `` |
| ifs | Insight title should be `` Ifs `` |
| switch | Insight title should be `` Switch `` |
| xor | Insight title should be `` Xor `` |
| what-are-logical-functions | Insight title should be `` What Are Logical Functions `` |
| ceiling-function | Insight title should be `` Ceiling `` |
| countunique-function | Insight title should be `` Countunique `` |
| even-odd-iseven-isodd | Insight title should be `` Even, Odd, Iseven & Isodd `` |
| floor-function | Insight title should be `` Floor `` |
| power-function | Insight title should be `` The Power Function `` |
| to-date | Insight title should be `` To_date `` |
| to-dollars | Insight title should be `` To_dollars `` |
| to-percent | Insight title should be `` To_percent `` |
| to-pure-number | Insight title should be `` To_pure_number `` |
| to-text | Insight title should be `` To_text `` |
| spreadsheet-shortcuts | Insight title should be `` Spreadsheet Shortcuts `` |
| always-check-function-range | Insight title should be `` Always Check Your Function Range `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-08-20 16:04 UTC, enki-hq commented
### Title

| File Name | Error Message |
|:-:|:-:|
| charts-2 | Workout title should be `` Charts Ii `` |
| functions-and-formulas-ii | Workout title should be `` Functions & Formulas Ii `` |
| functions-and-formulas-iii | Workout title should be `` Functions & Formulas Iii `` |
| logical-functions-ii | Workout title should be `` Logical Functions Ii `` |
| pivot-tables-ii | Workout title should be `` Pivot Tables Ii `` |
| always-check-functions-names | Insight title should be `` Always Check Function Names `` |
| spreadsheet-pemdas | Insight title should be `` Order of Operations `` |
| equals-and-eq | Insight title should be `` `=` and `Eq()` `` |
| greater-than-gt-greater-than-or-equal-gte | Insight title should be `` `>`, `>=`, `Gt()` & `Gte()` `` |
| less-than-lt-less-than-or-equal-lte | Insight title should be `` `<`, `<=`, `Lt()` & `Lte()` `` |
| not-equal-and-ne | Insight title should be `` `<>` & `Ne()` `` |
| averageif-countif | Insight title should be `` Averageif, Countif `` |
| min-max-average | Insight title should be `` `Min`, `Max`, `Average` `` |
| split | Insight title should be `` Split `` |
| concat | Insight title should be `` Concat `` |
| concatenate | Insight title should be `` Concatenate `` |
| proper | Insight title should be `` Proper `` |
| unique | Insight title should be `` Unique `` |
| detectlanguage | Insight title should be `` Detectlanguage `` |
| google-image | Insight title should be `` Image `` |
| googletranslate | Insight title should be `` Googletranslate `` |
| importfeed-options-and-example | Insight title should be `` =Importfeed() options & Example `` |
| importfeed | Insight title should be `` =Importfeed() `` |
| importhtml | Insight title should be `` =Importhtml() `` |
| importrange-example | Insight title should be `` =Importrange() example `` |
| importrange | Insight title should be `` =Importrange() `` |
| importxml | Insight title should be `` Importxml `` |
| iferror | Insight title should be `` Iferror `` |
| ifna | Insight title should be `` Ifna `` |
| ifs | Insight title should be `` Ifs `` |
| switch | Insight title should be `` Switch `` |
| xor | Insight title should be `` Xor `` |
| what-are-logical-functions | Insight title should be `` What Are Logical Functions `` |
| ceiling-function | Insight title should be `` Ceiling `` |
| countunique-function | Insight title should be `` Countunique `` |
| even-odd-iseven-isodd | Insight title should be `` Even, Odd, Iseven & Isodd `` |
| floor-function | Insight title should be `` Floor `` |
| power-function | Insight title should be `` The Power Function `` |
| to-date | Insight title should be `` To_date `` |
| to-dollars | Insight title should be `` To_dollars `` |
| to-percent | Insight title should be `` To_percent `` |
| to-pure-number | Insight title should be `` To_pure_number `` |
| to-text | Insight title should be `` To_text `` |
| spreadsheet-shortcuts | Insight title should be `` Spreadsheet Shortcuts `` |
| always-check-function-range | Insight title should be `` Always Check Your Function Range `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-08-24 09:00 UTC, enki-hq commented
### Title

| File Name | Error Message |
|:-:|:-:|
| tips-and-tricks-part-2 | Workout title should be `` Tips & Tricks Ii `` |
| equals-and-eq | Insight title should be `` `=` and `Eq()` `` |
| greater-than-gt-greater-than-or-equal-gte | Insight title should be `` `>`, `>=`, `Gt()` & `Gte()` `` |
| less-than-lt-less-than-or-equal-lte | Insight title should be `` `<`, `<=`, `Lt()` & `Lte()` `` |
| not-equal-and-ne | Insight title should be `` `<>` & `Ne()` `` |
| iferror | Insight title should be `` Iferror `` |
| ifna | Insight title should be `` Ifna `` |
| ifs | Insight title should be `` Ifs `` |
| switch | Insight title should be `` Switch `` |
| xor | Insight title should be `` Xor `` |
| detectlanguage | Insight title should be `` Detectlanguage `` |
| google-image | Insight title should be `` Image `` |
| googletranslate | Insight title should be `` Googletranslate `` |
| importfeed-options-and-example | Insight title should be `` =Importfeed() options & Example `` |
| importfeed | Insight title should be `` =Importfeed() `` |
| importhtml | Insight title should be `` =Importhtml() `` |
| importrange-example | Insight title should be `` =Importrange() example `` |
| importrange | Insight title should be `` =Importrange() `` |
| importxml | Insight title should be `` Importxml `` |
| and | Insight title should be `` And `` |
| if | Insight title should be `` If `` |
| not | Insight title should be `` Not `` |
| or | Insight title should be `` Or `` |
| ceiling-function | Insight title should be `` Ceiling `` |
| countunique-function | Insight title should be `` Countunique `` |
| even-odd-iseven-isodd | Insight title should be `` Even, Odd, Iseven & Isodd `` |
| floor-function | Insight title should be `` Floor `` |
| power-function | Insight title should be `` The Power Function `` |
| averageif-countif | Insight title should be `` Averageif, Countif `` |
| min-max-average | Insight title should be `` `Min`, `Max`, `Average` `` |
| split | Insight title should be `` Split `` |
| to-date | Insight title should be `` To_date `` |
| to-dollars | Insight title should be `` To_dollars `` |
| to-percent | Insight title should be `` To_percent `` |
| to-pure-number | Insight title should be `` To_pure_number `` |
| to-text | Insight title should be `` To_text `` |
| concat | Insight title should be `` Concat `` |
| concatenate | Insight title should be `` Concatenate `` |
| proper | Insight title should be `` Proper `` |
| unique | Insight title should be `` Unique `` |
| common-actions-shortcuts | Insight title should be `` Common Action Shortcuts `` |
| formatting-editing-shortcuts-ii | Insight title should be `` Formating & Editing Shortcuts Ii `` |
| navigation-shortcuts | Insight title should be `` Navigation Shortcuts `` |
| spreadsheet-shortcuts | Insight title should be `` Spreadsheet Shortcuts `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-08-24 09:03 UTC, kapnobatai137 requested changes

2020-08-24 09:03 UTC, kapnobatai137 commented on spreadsheets/functions-and-formulas/README.md
> +description: Get familiar with Sheets functions and formulas.
@Stefan-Stojanovic how does this sound?
```suggestion
description: Get familiar with functions and formulas in Google Sheets.
```

2020-08-24 10:03 UTC, enki-hq commented
### Title

| File Name | Error Message |
|:-:|:-:|
| tips-and-tricks-part-2 | Workout title should be `` Tips & Tricks Ii `` |
| equals-and-eq | Insight title should be `` `=` and `Eq()` `` |
| greater-than-gt-greater-than-or-equal-gte | Insight title should be `` `>`, `>=`, `Gt()` & `Gte()` `` |
| less-than-lt-less-than-or-equal-lte | Insight title should be `` `<`, `<=`, `Lt()` & `Lte()` `` |
| not-equal-and-ne | Insight title should be `` `<>` & `Ne()` `` |
| iferror | Insight title should be `` Iferror `` |
| ifna | Insight title should be `` Ifna `` |
| ifs | Insight title should be `` Ifs `` |
| switch | Insight title should be `` Switch `` |
| xor | Insight title should be `` Xor `` |
| detectlanguage | Insight title should be `` Detectlanguage `` |
| google-image | Insight title should be `` Image `` |
| googletranslate | Insight title should be `` Googletranslate `` |
| importfeed-options-and-example | Insight title should be `` =Importfeed() options & Example `` |
| importfeed | Insight title should be `` =Importfeed() `` |
| importhtml | Insight title should be `` =Importhtml() `` |
| importrange-example | Insight title should be `` =Importrange() example `` |
| importrange | Insight title should be `` =Importrange() `` |
| importxml | Insight title should be `` Importxml `` |
| and | Insight title should be `` And `` |
| if | Insight title should be `` If `` |
| not | Insight title should be `` Not `` |
| or | Insight title should be `` Or `` |
| ceiling-function | Insight title should be `` Ceiling `` |
| countunique-function | Insight title should be `` Countunique `` |
| even-odd-iseven-isodd | Insight title should be `` Even, Odd, Iseven & Isodd `` |
| floor-function | Insight title should be `` Floor `` |
| power-function | Insight title should be `` The Power Function `` |
| averageif-countif | Insight title should be `` Averageif, Countif `` |
| min-max-average | Insight title should be `` `Min`, `Max`, `Average` `` |
| split | Insight title should be `` Split `` |
| to-date | Insight title should be `` To_date `` |
| to-dollars | Insight title should be `` To_dollars `` |
| to-percent | Insight title should be `` To_percent `` |
| to-pure-number | Insight title should be `` To_pure_number `` |
| to-text | Insight title should be `` To_text `` |
| concat | Insight title should be `` Concat `` |
| concatenate | Insight title should be `` Concatenate `` |
| proper | Insight title should be `` Proper `` |
| unique | Insight title should be `` Unique `` |
| common-actions-shortcuts | Insight title should be `` Common Action Shortcuts `` |
| formatting-editing-shortcuts-ii | Insight title should be `` Formating & Editing Shortcuts Ii `` |
| navigation-shortcuts | Insight title should be `` Navigation Shortcuts `` |
| spreadsheet-shortcuts | Insight title should be `` Spreadsheet Shortcuts `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-08-24 10:15 UTC, enki-hq commented
### Title

| File Name | Error Message |
|:-:|:-:|
| tips-and-tricks-part-2 | Workout title should be `` Tips & Tricks Ii `` |
| equals-and-eq | Insight title should be `` `=` and `Eq()` `` |
| greater-than-gt-greater-than-or-equal-gte | Insight title should be `` `>`, `>=`, `Gt()` & `Gte()` `` |
| less-than-lt-less-than-or-equal-lte | Insight title should be `` `<`, `<=`, `Lt()` & `Lte()` `` |
| not-equal-and-ne | Insight title should be `` `<>` & `Ne()` `` |
| iferror | Insight title should be `` Iferror `` |
| ifna | Insight title should be `` Ifna `` |
| ifs | Insight title should be `` Ifs `` |
| switch | Insight title should be `` Switch `` |
| xor | Insight title should be `` Xor `` |
| detectlanguage | Insight title should be `` Detectlanguage `` |
| google-image | Insight title should be `` Image `` |
| googletranslate | Insight title should be `` Googletranslate `` |
| importfeed-options-and-example | Insight title should be `` =Importfeed() options & Example `` |
| importfeed | Insight title should be `` =Importfeed() `` |
| importhtml | Insight title should be `` =Importhtml() `` |
| importrange-example | Insight title should be `` =Importrange() example `` |
| importrange | Insight title should be `` =Importrange() `` |
| importxml | Insight title should be `` Importxml `` |
| and | Insight title should be `` And `` |
| if | Insight title should be `` If `` |
| not | Insight title should be `` Not `` |
| or | Insight title should be `` Or `` |
| ceiling-function | Insight title should be `` Ceiling `` |
| countunique-function | Insight title should be `` Countunique `` |
| even-odd-iseven-isodd | Insight title should be `` Even, Odd, Iseven & Isodd `` |
| floor-function | Insight title should be `` Floor `` |
| power-function | Insight title should be `` The Power Function `` |
| averageif-countif | Insight title should be `` Averageif, Countif `` |
| min-max-average | Insight title should be `` `Min`, `Max`, `Average` `` |
| split | Insight title should be `` Split `` |
| to-date | Insight title should be `` To_date `` |
| to-dollars | Insight title should be `` To_dollars `` |
| to-percent | Insight title should be `` To_percent `` |
| to-pure-number | Insight title should be `` To_pure_number `` |
| to-text | Insight title should be `` To_text `` |
| concat | Insight title should be `` Concat `` |
| concatenate | Insight title should be `` Concatenate `` |
| proper | Insight title should be `` Proper `` |
| unique | Insight title should be `` Unique `` |
| common-actions-shortcuts | Insight title should be `` Common Action Shortcuts `` |
| formatting-editing-shortcuts-ii | Insight title should be `` Formating & Editing Shortcuts Ii `` |
| navigation-shortcuts | Insight title should be `` Navigation Shortcuts `` |
| spreadsheet-shortcuts | Insight title should be `` Spreadsheet Shortcuts `` |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-08-24 10:17 UTC, kapnobatai137 submitted a review, later dismissed

2020-08-24 10:19 UTC, enki-hq commented
### Title

| File Name | Error Message |
|:-:|:-:|
| tips-and-tricks-part-2 | Workout title should be `` Tips & Tricks Ii `` |
| equals-and-eq | Insight title should be `` `=` and `Eq()` `` |
| greater-than-gt-greater-than-or-equal-gte | Insight title should be `` `>`, `>=`, `Gt()` & `Gte()` `` |
| less-than-lt-less-than-or-equal-lte | Insight title should be `` `<`, `<=`, `Lt()` & `Lte()` `` |
| not-equal-and-ne | Insight title should be `` `<>` & `Ne()` `` |
| iferror | Insight title should be `` Iferror `` |
| ifna | Insight title should be `` Ifna `` |
| ifs | Insight title should be `` Ifs `` |
| switch | Insight title should be `` Switch `` |
| xor | Insight title should be `` Xor `` |
| detectlanguage | Insight title should be `` Detectlanguage `` |
| google-image | Insight title should be `` Image `` |
| googletranslate | Insight title should be `` Googletranslate `` |
| importfeed-options-and-example | Insight title should be `` =Importfeed() options & Example `` |
| importfeed | Insight title should be `` =Importfeed() `` |
| importhtml | Insight title should be `` =Importhtml() `` |
| importrange-example | Insight title should be `` =Importrange() example `` |
| importrange | Insight title should be `` =Importrange() `` |
| importxml | Insight title should be `` Importxml `` |
| and | Insight title should be `` And `` |
| if | Insight title should be `` If `` |
| not | Insight title should be `` Not `` |
| or | Insight title should be `` Or `` |
| ceiling-function | Insight title should be `` Ceiling `` |
| countunique-function | Insight title should be `` Countunique `` |
| even-odd-iseven-isodd | Insight title should be `` Even, Odd, Iseven & Isodd `` |
| floor-function | Insight title should be `` Floor `` |
| power-function | Insight title should be `` The Power Function `` |
| averageif-countif | Insight title should be `` Averageif, Countif `` |
| min-max-average | Insight title should be `` `Min`, `Max`, `Average` `` |
| split | Insight title should be `` Split `` |
| to-date | Insight title should be `` To_date `` |
| to-dollars | Insight title should be `` To_dollars `` |
| to-percent | Insight title should be `` To_percent `` |
| to-pure-number | Insight title should be `` To_pure_number `` |
| to-text | Insight title should be `` To_text `` |
| concat | Insight title should be `` Concat `` |
| concatenate | Insight title should be `` Concatenate `` |
| proper | Insight title should be `` Proper `` |
| unique | Insight title should be `` Unique `` |
| formatting-editing-shortcuts-ii | Insight title should be `` Formating & Editing Shortcuts Ii `` |
| navigation-shortcuts | Insight title should be `` Navigation Shortcuts `` |
| spreadsheet-shortcuts | Insight title should be `` Spreadsheet Shortcuts `` |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-08-24 10:20 UTC, enki-hq commented
### Title

| File Name | Error Message |
|:-:|:-:|
| tips-and-tricks-part-2 | Workout title should be `` Tips & Tricks Ii `` |
| equals-and-eq | Insight title should be `` `=` and `Eq()` `` |
| greater-than-gt-greater-than-or-equal-gte | Insight title should be `` `>`, `>=`, `Gt()` & `Gte()` `` |
| less-than-lt-less-than-or-equal-lte | Insight title should be `` `<`, `<=`, `Lt()` & `Lte()` `` |
| not-equal-and-ne | Insight title should be `` `<>` & `Ne()` `` |
| iferror | Insight title should be `` Iferror `` |
| ifna | Insight title should be `` Ifna `` |
| ifs | Insight title should be `` Ifs `` |
| switch | Insight title should be `` Switch `` |
| xor | Insight title should be `` Xor `` |
| detectlanguage | Insight title should be `` Detectlanguage `` |
| google-image | Insight title should be `` Image `` |
| googletranslate | Insight title should be `` Googletranslate `` |
| importfeed-options-and-example | Insight title should be `` =Importfeed() options & Example `` |
| importfeed | Insight title should be `` =Importfeed() `` |
| importhtml | Insight title should be `` =Importhtml() `` |
| importrange-example | Insight title should be `` =Importrange() example `` |
| importrange | Insight title should be `` =Importrange() `` |
| importxml | Insight title should be `` Importxml `` |
| and | Insight title should be `` And `` |
| if | Insight title should be `` If `` |
| not | Insight title should be `` Not `` |
| or | Insight title should be `` Or `` |
| ceiling-function | Insight title should be `` Ceiling `` |
| countunique-function | Insight title should be `` Countunique `` |
| even-odd-iseven-isodd | Insight title should be `` Even, Odd, Iseven & Isodd `` |
| floor-function | Insight title should be `` Floor `` |
| power-function | Insight title should be `` The Power Function `` |
| averageif-countif | Insight title should be `` Averageif, Countif `` |
| min-max-average | Insight title should be `` `Min`, `Max`, `Average` `` |
| split | Insight title should be `` Split `` |
| to-date | Insight title should be `` To_date `` |
| to-dollars | Insight title should be `` To_dollars `` |
| to-percent | Insight title should be `` To_percent `` |
| to-pure-number | Insight title should be `` To_pure_number `` |
| to-text | Insight title should be `` To_text `` |
| concat | Insight title should be `` Concat `` |
| concatenate | Insight title should be `` Concatenate `` |
| proper | Insight title should be `` Proper `` |
| unique | Insight title should be `` Unique `` |
| formatting-editing-shortcuts-ii | Insight title should be `` Formating & Editing Shortcuts Ii `` |
| spreadsheet-shortcuts | Insight title should be `` Spreadsheet Shortcuts `` |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-08-24 10:21 UTC, enki-hq commented
### Title

| File Name | Error Message |
|:-:|:-:|
| tips-and-tricks-part-2 | Workout title should be `` Tips & Tricks Ii `` |
| equals-and-eq | Insight title should be `` `=` and `Eq()` `` |
| greater-than-gt-greater-than-or-equal-gte | Insight title should be `` `>`, `>=`, `Gt()` & `Gte()` `` |
| less-than-lt-less-than-or-equal-lte | Insight title should be `` `<`, `<=`, `Lt()` & `Lte()` `` |
| not-equal-and-ne | Insight title should be `` `<>` & `Ne()` `` |
| iferror | Insight title should be `` Iferror `` |
| ifna | Insight title should be `` Ifna `` |
| ifs | Insight title should be `` Ifs `` |
| switch | Insight title should be `` Switch `` |
| xor | Insight title should be `` Xor `` |
| detectlanguage | Insight title should be `` Detectlanguage `` |
| google-image | Insight title should be `` Image `` |
| googletranslate | Insight title should be `` Googletranslate `` |
| importfeed-options-and-example | Insight title should be `` =Importfeed() options & Example `` |
| importfeed | Insight title should be `` =Importfeed() `` |
| importhtml | Insight title should be `` =Importhtml() `` |
| importrange-example | Insight title should be `` =Importrange() example `` |
| importrange | Insight title should be `` =Importrange() `` |
| importxml | Insight title should be `` Importxml `` |
| and | Insight title should be `` And `` |
| if | Insight title should be `` If `` |
| not | Insight title should be `` Not `` |
| or | Insight title should be `` Or `` |
| ceiling-function | Insight title should be `` Ceiling `` |
| countunique-function | Insight title should be `` Countunique `` |
| even-odd-iseven-isodd | Insight title should be `` Even, Odd, Iseven & Isodd `` |
| floor-function | Insight title should be `` Floor `` |
| power-function | Insight title should be `` The Power Function `` |
| averageif-countif | Insight title should be `` Averageif, Countif `` |
| min-max-average | Insight title should be `` `Min`, `Max`, `Average` `` |
| split | Insight title should be `` Split `` |
| to-date | Insight title should be `` To_date `` |
| to-dollars | Insight title should be `` To_dollars `` |
| to-percent | Insight title should be `` To_percent `` |
| to-pure-number | Insight title should be `` To_pure_number `` |
| to-text | Insight title should be `` To_text `` |
| concat | Insight title should be `` Concat `` |
| concatenate | Insight title should be `` Concatenate `` |
| proper | Insight title should be `` Proper `` |
| unique | Insight title should be `` Unique `` |
| formatting-editing-shortcuts-ii | Insight title should be `` Formating & Editing Shortcuts Ii `` |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-08-24 10:21 UTC, kapnobatai137 approved these changes

2020-08-24 10:21 UTC, merged