[regex] Add 3 new Regex workouts
enkidevs/curriculum pull request #2320
Opened 2020-08-26 15:49 UTC by emmbow

2020-08-26 15:49 UTC, enki-hq commented
Failed parsing files: 
  - regular-expressions/introduction/practical-applications-ii/credit-cards-i.md: 
 > 	Cannot parse invalid footnotes

2020-08-26 15:54 UTC, enki-hq commented
Failed parsing files: 
  - regular-expressions/introduction/practical-applications-ii/credit-cards-i.md: 
 > 	Cannot parse invalid footnotes

2020-08-26 15:59 UTC, enki-hq commented
Failed parsing files: 
  - regular-expressions/introduction/regex-use-cases-ii/credit-cards-i.md: 
 > 	Cannot parse invalid footnotes

2020-08-26 16:02 UTC, enki-hq commented
Failed parsing files: 
  - regular-expressions/introduction/regex-use-cases-ii/credit-cards-i.md: 
 > 	Cannot parse invalid footnotes

2020-08-26 16:15 UTC, kapnobatai137 requested changes

2020-08-26 16:15 UTC, kapnobatai137 commented on regular-expressions/introduction/regex-use-cases-ii/credit-cards-i.md
> +[1. Credit Card Networks]
should be `:` instead of `.`
```suggestion
[1: Credit Card Networks]
```

2020-08-26 16:20 UTC, enki-hq commented
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| html-tags | Insight slug `html-tags` is not unique in the database. |
### Title

| File Name | Error Message |
|:-:|:-:|
| regex-use-cases-ii | Workout title should be `` Regex Use Cases Ii `` |
| regex-use-cases-iii | Workout title should be `` Regex Use Cases Iii `` |
| the-regexp-object | Insight title should be `` The Regexp Object `` |
| regex-email-address-checker-ii | Insight title should be `` Email Address Checker Ii `` |
| regex-password-validation-using-positive-lookaheads | Insight title should be `` Passwords Using Positive Lookaheads `` |
| credit-cards-ii | Insight title should be `` Credit Cards Ii `` |
| url | Insight title should be `` Urls `` |
| zip-codes | Insight title should be `` Zip Codes `` |
| html-tags | Insight title should be `` HTML Tags `` |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-08-26 16:21 UTC, kapnobatai137 commented
@emmbow if the title suggestions look weird (like saying `II` should be `Ii`), ignore them. there is a fix in the pipeline

2020-08-27 15:01 UTC, enki-hq commented
### Title

| File Name | Error Message |
|:-:|:-:|
| regex-use-cases-ii | Workout title should be `` Regex Use Cases Ii `` |
| regex-use-cases-iii | Workout title should be `` Regex Use Cases Iii `` |
| the-regexp-object | Insight title should be `` The Regexp Object `` |
| regex-email-address-checker-ii | Insight title should be `` Email Address Checker Ii `` |
| regex-password-validation-using-positive-lookaheads | Insight title should be `` Passwords Using Positive Lookaheads `` |
| credit-cards-ii | Insight title should be `` Credit Cards Ii `` |
| url | Insight title should be `` Urls `` |
| zip-codes | Insight title should be `` Zip Codes `` |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-09-02 09:24 UTC, kapnobatai137 requested changes

2020-09-02 09:24 UTC, kapnobatai137 commented on regular-expressions/introduction/regex-and-javascript/exec.md
> +	- '[.exec()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec){website}'
```suggestion
  - '[.exec()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec){website}'
```

2020-09-02 09:24 UTC, kapnobatai137 commented on regular-expressions/introduction/regex-and-javascript/test.md
> +	- '[.test()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test){website}'
```suggestion
  - '[.test()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test){website}'
```

2020-09-02 09:25 UTC, enki-hq commented
### Title

| File Name | Error Message |
|:-:|:-:|
| regex-use-cases-ii | Workout title should be `` Regex Use Cases Ii `` |
| regex-use-cases-iii | Workout title should be `` Regex Use Cases Iii `` |
| the-regexp-object | Insight title should be `` The Regexp Object `` |
| regex-email-address-checker-ii | Insight title should be `` Email Address Checker Ii `` |
| regex-password-validation-using-positive-lookaheads | Insight title should be `` Passwords Using Positive Lookaheads `` |
| credit-cards-ii | Insight title should be `` Credit Cards Ii `` |
| url | Insight title should be `` Urls `` |
| zip-codes | Insight title should be `` Zip Codes `` |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-09-02 09:58 UTC, enki-hq commented
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| html-tags | Insight slug `html-tags` is not unique in the database. |
### Title

| File Name | Error Message |
|:-:|:-:|
| regex-email-address-checker-ii | Insight title should be `` Email Address Checker Ii `` |
| regex-password-validation-using-positive-lookaheads | Insight title should be `` Passwords Using Positive Lookaheads `` |
| credit-cards-ii | Insight title should be `` Credit Cards Ii `` |
| url | Insight title should be `` Urls `` |
| zip-codes | Insight title should be `` Zip Codes `` |
| regex-basics | Insight title should be `` Regex Basics `` |
| regex-quantifiers-ii | Insight title should be `` Quantifiers Ii `` |
| regex-wildcards-ii | Insight title should be `` Wildcards Ii `` |
| regex-ranges-ii | Insight title should be `` Ranges Ii `` |
| the-regexp-object | Insight title should be `` The Regexp Object `` |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-09-02 10:00 UTC, enki-hq commented
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| html-tags | Insight slug `html-tags` is not unique in the database. |
### Title

| File Name | Error Message |
|:-:|:-:|
| regex-email-address-checker-ii | Insight title should be `` Email Address Checker Ii `` |
| regex-password-validation-using-positive-lookaheads | Insight title should be `` Passwords Using Positive Lookaheads `` |
| credit-cards-ii | Insight title should be `` Credit Cards Ii `` |
| url | Insight title should be `` Urls `` |
| zip-codes | Insight title should be `` Zip Codes `` |
| regex-basics | Insight title should be `` Regex Basics `` |
| regex-quantifiers-ii | Insight title should be `` Quantifiers Ii `` |
| regex-wildcards-ii | Insight title should be `` Wildcards Ii `` |
| regex-ranges-ii | Insight title should be `` Ranges Ii `` |
| the-regexp-object | Insight title should be `` The Regexp Object `` |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-09-02 10:08 UTC, enki-hq commented
### Title

| File Name | Error Message |
|:-:|:-:|
| regex-email-address-checker-ii | Insight title should be `` Email Address Checker Ii `` |
| regex-password-validation-using-positive-lookaheads | Insight title should be `` Passwords Using Positive Lookaheads `` |
| credit-cards-ii | Insight title should be `` Credit Cards Ii `` |
| url | Insight title should be `` Urls `` |
| zip-codes | Insight title should be `` Zip Codes `` |
| regex-basics | Insight title should be `` Regex Basics `` |
| regex-quantifiers-ii | Insight title should be `` Quantifiers Ii `` |
| regex-wildcards-ii | Insight title should be `` Wildcards Ii `` |
| regex-ranges-ii | Insight title should be `` Ranges Ii `` |
| the-regexp-object | Insight title should be `` The Regexp Object `` |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-09-02 10:12 UTC, kapnobatai137 approved these changes

2020-09-02 10:12 UTC, merged