Update using-printstream-format-to-format-a-string-before-printing.md
enkidevs/curriculum pull request #2369
Opened 2020-09-27 18:43 UTC by Stefan-Stojanovic

2020-09-27 18:44 UTC, enki-hq commented
### Topic

| Topic Name | Error Message |
|:-:|:-:|
| error-not-found | Topic should have at least one workout with the "workout" aspect. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-09-28 11:22 UTC, kapnobatai137 requested changes

2020-09-28 11:22 UTC, kapnobatai137 commented on java/data-management/strings-ii/using-printstream-format-to-format-a-string-before-printing.md
> +//System.out is Printstream object
we should add a space after comment characters (`//`) and I think the name is `PrintStream` ([source](https://docs.oracle.com/javase/7/docs/api/java/io/PrintStream.html))

```suggestion
// System.out is a PrintStream object
```

2020-09-28 12:18 UTC, enki-hq commented
### Topic

| Topic Name | Error Message |
|:-:|:-:|
| error-not-found | Topic should have at least one workout with the "workout" aspect. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-09-28 12:19 UTC, enki-hq commented
### Topic

| Topic Name | Error Message |
|:-:|:-:|
| error-not-found | Topic should have at least one workout with the "workout" aspect. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-09-28 12:21 UTC, enki-hq commented
### Topic

| Topic Name | Error Message |
|:-:|:-:|
| error-not-found | Topic should have at least one workout with the "workout" aspect. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-09-28 12:21 UTC, merged