Update searching-array-methods.md
enkidevs/curriculum pull request #2378
Opened 2020-10-01 13:46 UTC by Stefan-Stojanovic

Update incorrect information

If no elements match then *undefined* will be returned:

to:

If no elements match then `-1` will be returned:

and
//returns Alex
to:
//returns { name: 'Alex', age: 36 }

2020-10-01 13:46 UTC, enki-hq commented
### Topic

| Topic Name | Error Message |
|:-:|:-:|
| error-not-found | Topic should have at least one workout with the "workout" aspect. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-10-05 12:39 UTC, kapnobatai137 requested changes
@Stefan-Stojanovic 

we should also:
- replace `var` with `let` in the content, pq, and rq sections
- replace the `ponyfoo.com` resource title with `ES6 Array Extensions in Depth`
- delete the `inAlgoPools: false` line since it's not used anymore

2020-10-05 12:39 UTC, kapnobatai137 commented on javascript/ecmascript-2015/array-updates/searching-array-methods.md
> +//returns { name: 'Alex', age: 36 }
```suggestion
// returns { name: 'Alex', age: 36 }
```

2020-10-05 12:49 UTC, Stefan-Stojanovic commented on javascript/ecmascript-2015/array-updates/searching-array-methods.md
> +//returns { name: 'Alex', age: 36 }
Done

2020-10-05 12:49 UTC, enki-hq commented
### Topic

| Topic Name | Error Message |
|:-:|:-:|
| error-not-found | Topic should have at least one workout with the "workout" aspect. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-10-05 12:49 UTC, Stefan-Stojanovic commented
> @Stefan-Stojanovic
> 
> we should also:
> 
> * replace `var` with `let` in the content, pq, and rq sections
> * replace the `ponyfoo.com` resource title with `ES6 Array Extensions in Depth`
> * delete the `inAlgoPools: false` line since it's not used anymore

done

2020-10-05 12:51 UTC, kapnobatai137 submitted a review, later dismissed
:muscle:

2020-10-05 12:53 UTC, enki-hq commented
### Topic

| Topic Name | Error Message |
|:-:|:-:|
| error-not-found | Topic should have at least one workout with the "workout" aspect. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-10-05 12:55 UTC, enki-hq commented
### Topic

| Topic Name | Error Message |
|:-:|:-:|
| error-not-found | Topic should have at least one workout with the "workout" aspect. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-10-05 12:56 UTC, enki-hq commented
### Topic

| Topic Name | Error Message |
|:-:|:-:|
| error-not-found | Topic should have at least one workout with the "workout" aspect. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-10-05 12:56 UTC, merged