Update creating-classes.md
enkidevs/curriculum pull request #2393
Opened 2020-10-19 14:23 UTC by Stefan-Stojanovic

2020-10-19 14:23 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-10-19 16:09 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-10-20 08:45 UTC, kapnobatai137 requested changes
I left a couple of comments, mostly related to formatting

2020-10-20 08:45 UTC, kapnobatai137 commented on python/core/classes-i/creating-classes.md
> +To create a class is also called to "instantiate" and is done like so:
what do you think about this?
```suggestion
To create a class (also called to "instantiate") is done like so:
```

2020-10-20 08:45 UTC, kapnobatai137 commented on python/core/classes-i/creating-classes.md
> +However, what we just created is an empty *Employee* class. The newly instantiated object can't do anything. It needs a method.
```suggestion
However, what we just created is an empty `Employee` class. The newly instantiated object can't do anything. It needs a method.
```

2020-10-20 08:45 UTC, kapnobatai137 commented on python/core/classes-i/creating-classes.md
> +To define a method, for instance, the `__init__` method, we would have to do something like this:
what do you think about this?
```suggestion
To define a method (e.g. the `__init__` method) we would have to do something like this:
```

2020-10-20 08:45 UTC, kapnobatai137 commented on python/core/classes-i/creating-classes.md
> +Now that we have the initialization method we can pass some information when creating a new Employee:
```suggestion
Now that we have the initialization method we can pass some information when creating a new `Employee`:
```

2020-10-20 08:45 UTC, kapnobatai137 commented on python/core/classes-i/creating-classes.md
> +A block structure in python is determined with indentation.
how does this sound?
```suggestion
Block structures in Python are determined by their indentation.
```

2020-10-20 08:45 UTC, kapnobatai137 commented on python/core/classes-i/creating-classes.md
> +emp.message()
for the other examples in this insight we used 2 spaces for indentation. let's do the same for this code block:
```suggestion
class Employee:
  company = 'Enki'

  def __init__(self):
    print('Hello Enki')
 
  def message(self):
    print('Welcome to Enki')
 
emp = Employee() # Created an Instance

print('My company is: ', emp.company)
emp.message()
```

2020-10-20 08:45 UTC, kapnobatai137 commented on python/core/classes-i/creating-classes.md
> +In the "class Employee" block scope, we have the `def __init__` and `def message` methods.
```suggestion
In the block scope of the `Employee` class, we have the `__init__` and `message` methods.
```

2020-10-20 08:45 UTC, kapnobatai137 commented on python/core/classes-i/creating-classes.md
> +The `Employee` class can access both methods because they are in its block scope. (Shown with indentation.)
```suggestion
The `Employee` class can access both methods because they are in its block scope (shown with indentation). 
```

2020-10-20 08:45 UTC, kapnobatai137 commented on python/core/classes-i/creating-classes.md
> +The first code that is not a part of the class is the `emp = Employee()` instantiation.
```suggestion
The first line of code that is not a part of the `Employee`'s block scope is the instantiation `emp = Employee()`.
```

2020-10-20 11:50 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-10-20 11:50 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-10-20 11:51 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-10-20 11:51 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-10-20 11:51 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-10-20 11:51 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-10-20 11:52 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-10-20 11:52 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-10-20 11:53 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-10-20 11:53 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-10-20 12:46 UTC, kapnobatai137 submitted a review, later dismissed
:muscle:

2020-10-22 13:47 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-10-22 13:49 UTC, enki-hq commented
### Insight previews:
- [ ] [enkidevs/curriculum/python/core/classes-i/creating-classes.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/python/core/classes-i/creating-classes.md?ref=5844714094fb7230d6a5a24b5b67039254e2b193)

2020-10-22 14:11 UTC, merged