Update quick-cd-tips.md
enkidevs/curriculum pull request #2465
Opened 2020-12-03 10:11 UTC by Stefan-Stojanovic

improve the readability of the insight

2020-12-03 10:12 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-12-03 10:13 UTC, enki-hq commented
### Insight previews:
- [ ] [enkidevs/curriculum/linux/user-and-file-management/shell/quick-cd-tips.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/linux/user-and-file-management/shell/quick-cd-tips.md?ref=5a455346d1f4523a6bebe6604d2d1a27518e7bff)

2020-12-03 11:36 UTC, nem035 approved these changes

2021-03-22 11:26 UTC, kapnobatai137 requested changes
@Stefan-Stojanovic let's apply these suggestions and merge?

2021-03-22 11:26 UTC, kapnobatai137 commented on linux/user-and-file-management/shell/quick-cd-tips.md
> +To learn more about the directory stack or to view the differences between `popd` and `pushd` vs `cd` in both `bash` and `zsh`, check out the links in the "Learn More" section.
```suggestion
To learn more about the directory stack or to view the differences between `popd` and `pushd` vs `cd` in both `bash` and `zsh`, check out the links in the *Learn More* section.
```

2021-03-22 11:26 UTC, kapnobatai137 commented on linux/user-and-file-management/shell/quick-cd-tips.md
> +> The current directory is always the "top" of the directory stack.
```suggestion
> 💡 The current directory is always at *the top of the directory stack*.
```

2021-03-22 11:26 UTC, kapnobatai137 commented on linux/user-and-file-management/shell/quick-cd-tips.md
> +> Tilde `~` is a short hand notation for `Users/your-name/`.
```suggestion
> 💡 Tilde `~` is a shorthand notation for `Users/your-name/`.
```

2021-03-22 12:06 UTC, enki-hq commented
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| quick-cd-tips | Insight has a practice question but it's missing the `practiceQuestion` metadata field. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-03-22 12:06 UTC, enki-hq commented
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| quick-cd-tips | Insight has a practice question but it's missing the `practiceQuestion` metadata field. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-03-22 12:06 UTC, enki-hq commented
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| quick-cd-tips | Insight has a practice question but it's missing the `practiceQuestion` metadata field. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-03-22 12:11 UTC, kapnobatai137 approved these changes

2021-03-22 12:12 UTC, merged