Create core-html-elements-discussion-insight.md
enkidevs/curriculum pull request #2471
Opened 2020-12-07 09:44 UTC by Stefan-Stojanovic

footnotes might need updating

2020-12-07 09:44 UTC, enki-hq commented
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| core-html-elements-discussion-insight | No Enki username has been found for this author. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-12-07 09:46 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-12-07 09:48 UTC, enki-hq commented
### Insight previews:
- [ ] [enkidevs/curriculum/web/html/core-html-elements/core-html-elements-discussion-insight.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/web/html/core-html-elements/core-html-elements-discussion-insight.md?ref=9ea4dc12fee2fc9497158c15d2f85b8fefdeab5a)

2020-12-07 10:09 UTC, nem035 commented on web/html/core-html-elements/core-html-elements-discussion-insight.md
> +Here's one example of how the page can look:
I think "like" is missing here?

```suggestion
Here's one example of how the page can look like:
```

2020-12-07 10:11 UTC, nem035 submitted a review, later dismissed
:+1:

2020-12-07 10:30 UTC, kapnobatai137 approved these changes

2020-12-07 10:30 UTC, kapnobatai137 requested changes
@Stefan-Stojanovic you forgot to add the insight to the workout's README

2020-12-07 13:52 UTC, kapnobatai137 requested changes
@Stefan-Stojanovic please delete `parent: meta-elements` on line 5 in the workout's README ([here](https://github.com/enkidevs/curriculum/pull/2471/files#diff-a2a76c783df3fa94ac8c1827af8003ab3db9d4d12df1f8233100ff2ce358de2cR5))

2020-12-07 19:22 UTC, nem035 submitted a review, later dismissed

2020-12-08 13:59 UTC, kapnobatai137 approved these changes

2020-12-08 17:50 UTC, merged