Update splice.md
enkidevs/curriculum pull request #2504
Opened 2020-12-17 12:18 UTC by Stefan-Stojanovic

Closing [this PR](https://github.com/enkidevs/curriculum/pull/2492) because of the structural changes and creating this one with the same changes

2020-12-17 12:19 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-12-17 12:20 UTC, enki-hq commented
### Insight previews:
- [ ] [enkidevs/curriculum/javascript/javascript-core/javascript-arrays/splice.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/javascript-arrays/splice.md?ref=26c0dae1e4fe46a16157b4aade51a48c0e5da6d4)

2020-12-18 15:00 UTC, kapnobatai137 requested changes

2020-12-18 15:00 UTC, kapnobatai137 commented on javascript/javascript-core/javascript-arrays/splice.md
> +It accepts 3 arguments with the 2nd and 3rd being optional:
how does this sound?

```suggestion
It accepts three arguments, with **only the first being mandatory**:
```

2020-12-18 15:00 UTC, kapnobatai137 commented on javascript/javascript-core/javascript-arrays/splice.md
> +If *Delete* is omitted, splice will remove all elements from the specified *Start* to the end of the array. On the other hand, if its 0 or a negative number, it won't delete any elements.
```suggestion
If the *Delete* argument is omitted, `splice` will remove all elements from the specified *Start* to the end of the array. On the other hand, if it's `0` or a negative number, it won't delete any elements.
```

2020-12-18 15:27 UTC, kapnobatai137 approved these changes

2020-12-18 15:32 UTC, merged