SQL - Insert
enkidevs/curriculum pull request #2512
Opened 2020-12-22 15:29 UTC by kapnobatai137

- new discussion insight in the insert workout

2020-12-22 15:30 UTC, enki-hq commented
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| insert-discussion-insight | <ul><li>`Playground` pointing to `https://student.enkicamp.com/public/playground?jsonUrl=https%3A%2F%2Fgist.githubusercontent.com%2Fkapnobatai137%2F757d2557a971940305ace59e5bce0808%2Fraw%2F32399b94024073c351727c6888a697f9fa448737%2Fsql-insert-discussion-insight.json` is broken because `HTTP_404`</li></ul> |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-12-22 15:30 UTC, enki-hq commented
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| insert-discussion-insight | <ul><li>`Playground` pointing to `https://student.enkicamp.com/public/playground?jsonUrl=https%3A%2F%2Fgist.githubusercontent.com%2Fkapnobatai137%2F757d2557a971940305ace59e5bce0808%2Fraw%2F32399b94024073c351727c6888a697f9fa448737%2Fsql-insert-discussion-insight.json` is broken because `HTTP_404`</li></ul> |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-01-14 12:00 UTC, Stefan-Stojanovic requested changes

2021-01-14 12:00 UTC, Stefan-Stojanovic commented on sql/dml/insert/insert-discussion-insight.md
> +It's also up to you to choose the rating system. We have *No Country For Old Men* a nine out of ten, but you can use anything **as long as it's a number**.
```suggestion
It's also up to you to choose the rating system. We gave *No Country For Old Men* a nine out of ten, but you can use anything **as long as it's a number**.
```

2021-01-18 16:46 UTC, enki-hq commented
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| insert-discussion-insight | <ul><li>`Playground` pointing to `https://learner.enkicamp.com/public/playground?jsonUrl=https%3A%2F%2Fgist.githubusercontent.com%2Fkapnobatai137%2F757d2557a971940305ace59e5bce0808%2Fraw%2F32399b94024073c351727c6888a697f9fa448737%2Fsql-insert-discussion-insight.json` is broken because `HTTP_404`</li></ul> |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-01-18 16:47 UTC, enki-hq commented
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| insert-discussion-insight | <ul><li>`Playground` pointing to `https://learner.enkicamp.com/public/playground?jsonUrl=https%3A%2F%2Fgist.githubusercontent.com%2Fkapnobatai137%2F757d2557a971940305ace59e5bce0808%2Fraw%2F32399b94024073c351727c6888a697f9fa448737%2Fsql-insert-discussion-insight.json` is broken because `HTTP_404`</li></ul> |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-01-18 16:48 UTC, merged