SQL - Update
enkidevs/curriculum pull request #2523
Opened 2020-12-30 10:47 UTC by kapnobatai137

- sql update discussion insight

2020-12-30 10:47 UTC, enki-hq commented
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| update-discussion-insight | <ul><li>`Playground` pointing to `https://student.enkicamp.com/public/playground?jsonUrl=https%3A%2F%2Fgist.githubusercontent.com%2Fkapnobatai137%2Fa41bb442321200a0ded3475100e5f9a9%2Fraw%2Ff7f2ef8a49bd551c39b5fa2a8255d62a72ff1f73%2Fsql-update-discussion-insight.json` is broken because `HTTP_404`</li></ul> |

> If you notice anything wrong with these rules contact andrei@enki.com.

2020-12-30 10:48 UTC, enki-hq commented
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| update-discussion-insight | <ul><li>`Playground` pointing to `https://student.enkicamp.com/public/playground?jsonUrl=https%3A%2F%2Fgist.githubusercontent.com%2Fkapnobatai137%2Fa41bb442321200a0ded3475100e5f9a9%2Fraw%2Ff7f2ef8a49bd551c39b5fa2a8255d62a72ff1f73%2Fsql-update-discussion-insight.json` is broken because `HTTP_404`</li></ul> |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-01-14 12:03 UTC, Stefan-Stojanovic requested changes

2021-01-14 12:03 UTC, Stefan-Stojanovic commented on sql/dml/update/update-discussion-insight.md
> +Consider the following table `movies` table:
```suggestion
Consider the following `movies` table:
```

2021-01-18 16:29 UTC, enki-hq commented
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| update-discussion-insight | <ul><li>`Playground` pointing to `https://learner.enkicamp.com/public/playground?jsonUrl=https%3A%2F%2Fgist.githubusercontent.com%2Fkapnobatai137%2Fa41bb442321200a0ded3475100e5f9a9%2Fraw%2F000ef19e1786ccc4ca5f846ad98ef2b27b38c189%2Fsql-update-discussion-insight.json` is broken because `HTTP_404`</li></ul> |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-01-18 16:29 UTC, enki-hq commented
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| update-discussion-insight | <ul><li>`Playground` pointing to `https://learner.enkicamp.com/public/playground?jsonUrl=https%3A%2F%2Fgist.githubusercontent.com%2Fkapnobatai137%2Fa41bb442321200a0ded3475100e5f9a9%2Fraw%2F000ef19e1786ccc4ca5f846ad98ef2b27b38c189%2Fsql-update-discussion-insight.json` is broken because `HTTP_404`</li></ul> |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-01-18 16:36 UTC, enki-hq commented
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| update-discussion-insight | <ul><li>`Playground` pointing to `https://learner.enkicamp.com/public/playground?jsonUrl=https%3A%2F%2Fgist.githubusercontent.com%2Fkapnobatai137%2Fa41bb442321200a0ded3475100e5f9a9%2Fraw%2F000ef19e1786ccc4ca5f846ad98ef2b27b38c189%2Fsql-update-discussion-insight.json` is broken because `HTTP_404`</li></ul> |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-01-18 16:37 UTC, merged