Update position-elements-with-position-sticky.md
enkidevs/curriculum pull request #2578
Opened 2021-01-28 09:04 UTC by Stefan-Stojanovic

Remove incorrect and irrelevant question

2021-01-28 09:04 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-01-28 09:05 UTC, enki-hq commented
### Insight previews:
- [ ] [enkidevs/curriculum/web/styling/positioning-tips/position-elements-with-position-sticky.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/web/styling/positioning-tips/position-elements-with-position-sticky.md?ref=b950c48463f10ee0f603919b895268c57ae6666e)

2021-01-28 09:13 UTC, kapnobatai137 commented
@Stefan-Stojanovic can we replace it with a different question? something like "How can you make the X class sticky?"

2021-01-28 10:47 UTC, nem035 commented
Yeah, I'd lean on the side of never removing questions. If anything, we should always strive to add new ones (and in this case we should probably add a better one)

2021-01-29 10:30 UTC, kapnobatai137 requested changes
let's change the class name to `enki` instead of `some-class`?

2021-01-29 10:30 UTC, kapnobatai137 commented on web/styling/positioning-tips/position-elements-with-position-sticky.md
> +Can you make the `.some-class` class sticky?
```suggestion
Can you make the `.enki` class sticky?
```

2021-01-29 10:30 UTC, kapnobatai137 commented on web/styling/positioning-tips/position-elements-with-position-sticky.md
> +.some-class{
```suggestion
.enki {
```

2021-02-01 11:43 UTC, kapnobatai137 approved these changes

2021-02-01 14:46 UTC, merged