Type in the gap Webflow
enkidevs/curriculum pull request #2588
Opened 2021-02-01 20:28 UTC by Stefan-Stojanovic

2021-02-01 20:28 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-02-01 20:39 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-02-01 20:41 UTC, enki-hq commented
### Insight previews:
- [ ] [enkidevs/curriculum/nocode-webflow/webflow-introduction/basics-of-web/element-hierarchy.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/nocode-webflow/webflow-introduction/basics-of-web/element-hierarchy.md?ref=764fa078460ba032b1d754b0317a7380ee37100b)
- [ ] [enkidevs/curriculum/nocode-webflow/webflow-introduction/basics-of-web/the-element-panel.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/nocode-webflow/webflow-introduction/basics-of-web/the-element-panel.md?ref=764fa078460ba032b1d754b0317a7380ee37100b)
- [ ] [enkidevs/curriculum/nocode-webflow/webflow-introduction/basics-of-web/webflow-the-box-model.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/nocode-webflow/webflow-introduction/basics-of-web/webflow-the-box-model.md?ref=764fa078460ba032b1d754b0317a7380ee37100b)
- [ ] [enkidevs/curriculum/nocode-webflow/webflow-introduction/diy/columns.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/nocode-webflow/webflow-introduction/diy/columns.md?ref=764fa078460ba032b1d754b0317a7380ee37100b)
- [ ] [enkidevs/curriculum/nocode-webflow/webflow-introduction/diy/containers.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/nocode-webflow/webflow-introduction/diy/containers.md?ref=764fa078460ba032b1d754b0317a7380ee37100b)
- [ ] [enkidevs/curriculum/nocode-webflow/webflow-introduction/diy/divisions.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/nocode-webflow/webflow-introduction/diy/divisions.md?ref=764fa078460ba032b1d754b0317a7380ee37100b)
- [ ] [enkidevs/curriculum/nocode-webflow/webflow-introduction/diy/getting-started.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/nocode-webflow/webflow-introduction/diy/getting-started.md?ref=764fa078460ba032b1d754b0317a7380ee37100b)
- [ ] [enkidevs/curriculum/nocode-webflow/webflow-introduction/diy/sections.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/nocode-webflow/webflow-introduction/diy/sections.md?ref=764fa078460ba032b1d754b0317a7380ee37100b)
- [ ] [enkidevs/curriculum/nocode-webflow/webflow-introduction/intro-components/forms.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/nocode-webflow/webflow-introduction/intro-components/forms.md?ref=764fa078460ba032b1d754b0317a7380ee37100b)
- [ ] [enkidevs/curriculum/nocode-webflow/webflow-introduction/intro-components/navigation.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/nocode-webflow/webflow-introduction/intro-components/navigation.md?ref=764fa078460ba032b1d754b0317a7380ee37100b)
- [ ] [enkidevs/curriculum/nocode-webflow/webflow-introduction/intro-components/sliders.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/nocode-webflow/webflow-introduction/intro-components/sliders.md?ref=764fa078460ba032b1d754b0317a7380ee37100b)
- [ ] [enkidevs/curriculum/nocode-webflow/webflow-introduction/intro-components/symbols.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/nocode-webflow/webflow-introduction/intro-components/symbols.md?ref=764fa078460ba032b1d754b0317a7380ee37100b)
- [ ] [enkidevs/curriculum/nocode-webflow/webflow-introduction/layouts/webflow-display-settings.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/nocode-webflow/webflow-introduction/layouts/webflow-display-settings.md?ref=764fa078460ba032b1d754b0317a7380ee37100b)
- [ ] [enkidevs/curriculum/nocode-webflow/webflow-introduction/layouts/webflow-flexbox.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/nocode-webflow/webflow-introduction/layouts/webflow-flexbox.md?ref=764fa078460ba032b1d754b0317a7380ee37100b)
- [ ] [enkidevs/curriculum/nocode-webflow/webflow-introduction/layouts/webflow-margins.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/nocode-webflow/webflow-introduction/layouts/webflow-margins.md?ref=764fa078460ba032b1d754b0317a7380ee37100b)
- [ ] [enkidevs/curriculum/nocode-webflow/webflow-introduction/layouts/webflow-overviews.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/nocode-webflow/webflow-introduction/layouts/webflow-overviews.md?ref=764fa078460ba032b1d754b0317a7380ee37100b)
- [ ] [enkidevs/curriculum/nocode-webflow/webflow-introduction/layouts/webflow-paddings.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/nocode-webflow/webflow-introduction/layouts/webflow-paddings.md?ref=764fa078460ba032b1d754b0317a7380ee37100b)
- [ ] [enkidevs/curriculum/nocode-webflow/webflow-introduction/style/classes.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/nocode-webflow/webflow-introduction/style/classes.md?ref=764fa078460ba032b1d754b0317a7380ee37100b)
- [ ] [enkidevs/curriculum/nocode-webflow/webflow-introduction/style/states.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/nocode-webflow/webflow-introduction/style/states.md?ref=764fa078460ba032b1d754b0317a7380ee37100b)
- [ ] [enkidevs/curriculum/nocode-webflow/webflow-introduction/style/the-style-panel.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/nocode-webflow/webflow-introduction/style/the-style-panel.md?ref=764fa078460ba032b1d754b0317a7380ee37100b)
- [ ] [enkidevs/curriculum/nocode-webflow/webflow-introduction/style/webflow-html-tags.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/nocode-webflow/webflow-introduction/style/webflow-html-tags.md?ref=764fa078460ba032b1d754b0317a7380ee37100b)
- [ ] [enkidevs/curriculum/nocode-webflow/webflow-introduction/webflow-templates-i/filter-templates.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/nocode-webflow/webflow-introduction/webflow-templates-i/filter-templates.md?ref=764fa078460ba032b1d754b0317a7380ee37100b)
- [ ] [enkidevs/curriculum/nocode-webflow/webflow-introduction/webflow-templates-i/quick-start.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/nocode-webflow/webflow-introduction/webflow-templates-i/quick-start.md?ref=764fa078460ba032b1d754b0317a7380ee37100b)
- [ ] [enkidevs/curriculum/nocode-webflow/webflow-introduction/webflow-templates-i/template-example.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/nocode-webflow/webflow-introduction/webflow-templates-i/template-example.md?ref=764fa078460ba032b1d754b0317a7380ee37100b)
- [ ] [enkidevs/curriculum/nocode-webflow/webflow-introduction/webflow-templates-i/where-to-find-templates.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/nocode-webflow/webflow-introduction/webflow-templates-i/where-to-find-templates.md?ref=764fa078460ba032b1d754b0317a7380ee37100b)
- [ ] [enkidevs/curriculum/nocode-webflow/webflow-introduction/webflow-templates-ii/webflow-template-editing-2.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/nocode-webflow/webflow-introduction/webflow-templates-ii/webflow-template-editing-2.md?ref=764fa078460ba032b1d754b0317a7380ee37100b)
- [ ] [enkidevs/curriculum/nocode-webflow/webflow-introduction/webflow-templates-ii/webflow-template-editing-3.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/nocode-webflow/webflow-introduction/webflow-templates-ii/webflow-template-editing-3.md?ref=764fa078460ba032b1d754b0317a7380ee37100b)
- [ ] [enkidevs/curriculum/nocode-webflow/webflow-introduction/what-is-webflow/css.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/nocode-webflow/webflow-introduction/what-is-webflow/css.md?ref=764fa078460ba032b1d754b0317a7380ee37100b)
- [ ] [enkidevs/curriculum/nocode-webflow/webflow-introduction/what-is-webflow/html.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/nocode-webflow/webflow-introduction/what-is-webflow/html.md?ref=764fa078460ba032b1d754b0317a7380ee37100b)
- [ ] [enkidevs/curriculum/nocode-webflow/webflow-introduction/what-is-webflow/the-designer.m [...]

2021-03-22 14:28 UTC, kapnobatai137 requested changes

2021-03-22 14:28 UTC, kapnobatai137 commented on nocode-webflow/webflow-introduction/diy/divisions.md
> +    - type-in-the-gap
```suggestion
```

2021-03-22 14:31 UTC, kapnobatai137 approved these changes

2021-03-22 14:31 UTC, merged