type in the gap to applicable questions blockchain
enkidevs/curriculum pull request #2591
Opened 2021-02-01 22:40 UTC by Stefan-Stojanovic

2021-02-01 22:40 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-02-01 23:08 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-02-01 23:11 UTC, enki-hq commented
### Insight previews:
- [ ] [enkidevs/curriculum/blockchain/blockchain-fundamentals/altcoins/altcoins.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/blockchain/blockchain-fundamentals/altcoins/altcoins.md?ref=573d1b5c60c8fae5105ddc2e5519220042cdf5b4)
- [ ] [enkidevs/curriculum/blockchain/blockchain-fundamentals/altcoins/why-is-it-worth-having-multiple-coins.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/blockchain/blockchain-fundamentals/altcoins/why-is-it-worth-having-multiple-coins.md?ref=573d1b5c60c8fae5105ddc2e5519220042cdf5b4)
- [ ] [enkidevs/curriculum/blockchain/blockchain-fundamentals/anonimity/anonymity.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/blockchain/blockchain-fundamentals/anonimity/anonymity.md?ref=573d1b5c60c8fae5105ddc2e5519220042cdf5b4)
- [ ] [enkidevs/curriculum/blockchain/blockchain-fundamentals/anonimity/how-to-de-anonymize-bitcoin.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/blockchain/blockchain-fundamentals/anonimity/how-to-de-anonymize-bitcoin.md?ref=573d1b5c60c8fae5105ddc2e5519220042cdf5b4)
- [ ] [enkidevs/curriculum/blockchain/blockchain-fundamentals/anonimity/mixing.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/blockchain/blockchain-fundamentals/anonimity/mixing.md?ref=573d1b5c60c8fae5105ddc2e5519220042cdf5b4)
- [ ] [enkidevs/curriculum/blockchain/blockchain-fundamentals/building-the-ledger/consensus.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/blockchain/blockchain-fundamentals/building-the-ledger/consensus.md?ref=573d1b5c60c8fae5105ddc2e5519220042cdf5b4)
- [ ] [enkidevs/curriculum/blockchain/blockchain-fundamentals/building-the-ledger/malicious-nodes.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/blockchain/blockchain-fundamentals/building-the-ledger/malicious-nodes.md?ref=573d1b5c60c8fae5105ddc2e5519220042cdf5b4)
- [ ] [enkidevs/curriculum/blockchain/blockchain-fundamentals/building-the-ledger/the-ledger.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/blockchain/blockchain-fundamentals/building-the-ledger/the-ledger.md?ref=573d1b5c60c8fae5105ddc2e5519220042cdf5b4)
- [ ] [enkidevs/curriculum/blockchain/blockchain-fundamentals/building-the-ledger/the-utxo-model.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/blockchain/blockchain-fundamentals/building-the-ledger/the-utxo-model.md?ref=573d1b5c60c8fae5105ddc2e5519220042cdf5b4)
- [ ] [enkidevs/curriculum/blockchain/blockchain-fundamentals/building-the-ledger/verifying-the-ledger-ii.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/blockchain/blockchain-fundamentals/building-the-ledger/verifying-the-ledger-ii.md?ref=573d1b5c60c8fae5105ddc2e5519220042cdf5b4)
- [ ] [enkidevs/curriculum/blockchain/blockchain-fundamentals/building-the-ledger/verifying-the-ledger-iii.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/blockchain/blockchain-fundamentals/building-the-ledger/verifying-the-ledger-iii.md?ref=573d1b5c60c8fae5105ddc2e5519220042cdf5b4)
- [ ] [enkidevs/curriculum/blockchain/blockchain-fundamentals/building-the-ledger/verifying-the-ledger.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/blockchain/blockchain-fundamentals/building-the-ledger/verifying-the-ledger.md?ref=573d1b5c60c8fae5105ddc2e5519220042cdf5b4)
- [ ] [enkidevs/curriculum/blockchain/blockchain-fundamentals/consensus-algorithms/byzantine-fault-tolerance.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/blockchain/blockchain-fundamentals/consensus-algorithms/byzantine-fault-tolerance.md?ref=573d1b5c60c8fae5105ddc2e5519220042cdf5b4)
- [ ] [enkidevs/curriculum/blockchain/blockchain-fundamentals/consensus-algorithms/consensus-algorithms.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/blockchain/blockchain-fundamentals/consensus-algorithms/consensus-algorithms.md?ref=573d1b5c60c8fae5105ddc2e5519220042cdf5b4)
- [ ] [enkidevs/curriculum/blockchain/blockchain-fundamentals/consensus-algorithms/delegated-proof-of-stake.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/blockchain/blockchain-fundamentals/consensus-algorithms/delegated-proof-of-stake.md?ref=573d1b5c60c8fae5105ddc2e5519220042cdf5b4)
- [ ] [enkidevs/curriculum/blockchain/blockchain-fundamentals/consensus-algorithms/proof-of-stake.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/blockchain/blockchain-fundamentals/consensus-algorithms/proof-of-stake.md?ref=573d1b5c60c8fae5105ddc2e5519220042cdf5b4)
- [ ] [enkidevs/curriculum/blockchain/blockchain-fundamentals/consensus-algorithms/proof-of-work.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/blockchain/blockchain-fundamentals/consensus-algorithms/proof-of-work.md?ref=573d1b5c60c8fae5105ddc2e5519220042cdf5b4)
- [ ] [enkidevs/curriculum/blockchain/blockchain-fundamentals/cryptoeconomics/cryptoeconomics.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/blockchain/blockchain-fundamentals/cryptoeconomics/cryptoeconomics.md?ref=573d1b5c60c8fae5105ddc2e5519220042cdf5b4)
- [ ] [enkidevs/curriculum/blockchain/blockchain-fundamentals/cryptoeconomics/how-do-cryptocurrencies-acquire-value.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/blockchain/blockchain-fundamentals/cryptoeconomics/how-do-cryptocurrencies-acquire-value.md?ref=573d1b5c60c8fae5105ddc2e5519220042cdf5b4)
- [ ] [enkidevs/curriculum/blockchain/blockchain-fundamentals/cryptoeconomics/why-is-the-price-fluctuating-so-much.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/blockchain/blockchain-fundamentals/cryptoeconomics/why-is-the-price-fluctuating-so-much.md?ref=573d1b5c60c8fae5105ddc2e5519220042cdf5b4)
- [ ] [enkidevs/curriculum/blockchain/blockchain-fundamentals/ethereum-i/ethereum-and-ether.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/blockchain/blockchain-fundamentals/ethereum-i/ethereum-and-ether.md?ref=573d1b5c60c8fae5105ddc2e5519220042cdf5b4)
- [ ] [enkidevs/curriculum/blockchain/blockchain-fundamentals/ethereum-i/what-are-smart-contracts.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/blockchain/blockchain-fundamentals/ethereum-i/what-are-smart-contracts.md?ref=573d1b5c60c8fae5105ddc2e5519220042cdf5b4)
- [ ] [enkidevs/curriculum/blockchain/blockchain-fundamentals/ethereum-i/what-does-ethereum-do-differently-ii.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/blockchain/blockchain-fundamentals/ethereum-i/what-does-ethereum-do-differently-ii.md?ref=573d1b5c60c8fae5105ddc2e5519220042cdf5b4)
- [ ] [enkidevs/curriculum/blockchain/blockchain-fundamentals/ethereum-i/what-does-ethereum-do-differently.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/blockchain/blockchain-fundamentals/ethereum-i/what-does-ethereum-do-differently.md?ref=573d1b5c60c8fae5105ddc2e5519220042cdf5b4)
- [ ] [enkidevs/curriculum/blockchain/blockchain-fundamentals/ethereum-ii/erc20-tokens.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/blockchain/blockchain-fundamentals/ethereum-ii/erc20-tokens.md?ref=573d1b5c60c8fae5105ddc2e5519220042cdf5b4)
- [ ] [enkidevs/curriculum/blockchain/blockchain-fundamentals/ethereum-ii/erc721-tokens.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/blockchain/blockchain-fundamentals/ethereum-ii/erc721-tokens.md?ref=573d1b5c60c8fae5105ddc2e5519220042cdf5b4)
- [ ] [enkidevs/curriculum/blockchain/blockchain-fundamentals/ethereum-ii/initial-coin-offerings.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/blockchain/blockchain-fundamentals/ethereum-ii/initial-coin-offerings.md?ref=573d1b5c60c8fae5105ddc2e5519220042cdf5b4)
- [ ] [enkidevs/curriculum/blockchain/blockchain-fundamentals/ethereum-ii/token-standards.md](https://app.enkipro.com/public/preview-in [...]

2021-03-22 14:44 UTC, enki-hq commented
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| the-bitcoin-block | <ul><li>`First block mined` pointing to `https://blockchain.info/block/000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f` is broken because `HTTP_404`</li></ul> |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-03-22 14:56 UTC, enki-hq commented
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| the-bitcoin-block | <ul><li>`First block mined` pointing to `https://www.blockchain.com/btc/block/000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f` is broken because `HTTP_404`</li></ul> |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-03-22 14:58 UTC, kapnobatai137 requested changes

2021-03-22 14:58 UTC, kapnobatai137 commented on blockchain/blockchain-fundamentals/ethereum-i/what-does-ethereum-do-differently-ii.md
> +    - type-in-the-gap
```suggestion
```

2021-03-22 14:58 UTC, kapnobatai137 commented on blockchain/blockchain-fundamentals/the-bitcoin-blockchain/the-bitcoin-blockchain.md
> +    - type-in-the-gap
```suggestion
```

2021-03-22 14:59 UTC, kapnobatai137 approved these changes

2021-03-22 14:59 UTC, enki-hq commented
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| the-bitcoin-block | <ul><li>`First block mined` pointing to `https://www.blockchain.com/btc/block/000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f` is broken because `HTTP_404`</li></ul> |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-03-22 14:59 UTC, merged