Update notebooks.md
enkidevs/curriculum pull request #2643
Opened 2021-03-10 16:07 UTC by nem035

2021-03-10 16:07 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-03-10 16:21 UTC, Stefan-Stojanovic requested changes

2021-03-10 16:21 UTC, Stefan-Stojanovic commented on python-data-analysis/python-data-analysis-core/analysis-environments/notebooks.md
> +Each piece of code can be run and tested independently from other code. Y can also run all of the code at once.
```suggestion
Each piece of code can be run and tested independently from other code. You can also run all of the code at once.
```

2021-03-10 16:26 UTC, enki-hq commented
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| notebooks | No matching footnotes found. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-03-10 16:27 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-03-11 13:13 UTC, enki-hq commented
### Insight previews:
- [ ] [enkidevs/curriculum/python-data-analysis/python-data-analysis-core/analysis-environments/notebooks.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python-data-analysis/python-data-analysis-core/analysis-environments/notebooks.md?ref=a60c10a5ff5f7a19ea7e0f73fc2cab4620af5355)

2021-03-11 13:14 UTC, Stefan-Stojanovic approved these changes

2021-03-11 13:15 UTC, merged