Update programs-and-data.md
enkidevs/curriculum pull request #2660
Opened 2021-03-23 11:37 UTC by Stefan-Stojanovic

Add peanut butter and jelly youtube video to the content

2021-03-23 11:37 UTC, enki-hq commented
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| programs-and-data | Link checking took too long. Verify it manually. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-03-23 11:39 UTC, enki-hq commented
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| programs-and-data | Link checking took too long. Verify it manually. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-03-23 19:41 UTC, nem035 commented on coding-intro/coding-intro-core/core-concepts/programs-and-data.md
> +    [PB & J Sandwitch](youtube.com/watch?v=Ct-lOOUqmyY){website}
```suggestion
    [PB & J Sandwitch](https://youtube.com/watch?v=Ct-lOOUqmyY){website}
```

2021-03-23 19:43 UTC, nem035 commented on coding-intro/coding-intro-core/core-concepts/programs-and-data.md
> +> Check out the *Learn more* section to see two kids writing instructions to their programmer dad on how to make a peanut butter and jelly sandwich.
```suggestion
> Check out the *Learn more* section for a realistic (and funny) example of this 🤓
```

2021-03-23 19:45 UTC, enki-hq commented
### Insight previews:
- [ ] [enkidevs/curriculum/coding-intro/coding-intro-core/core-concepts/programs-and-data.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/coding-intro/coding-intro-core/core-concepts/programs-and-data.md?ref=cc92168bb5b50f9fff8e4b914ee2d2d9337833c9)

2021-03-23 19:56 UTC, nem035 commented on coding-intro/coding-intro-core/core-concepts/programs-and-data.md
> +    [EXACT instructions Challenge](https://youtube.com/watch?v=Ct-lOOUqmyY){website}
```suggestion
    [EXACT Instructions Challenge](https://youtube.com/watch?v=Ct-lOOUqmyY){website}
```

2021-03-24 10:10 UTC, nem035 submitted a review, later dismissed

2021-03-29 09:14 UTC, kapnobatai137 requested changes

2021-03-29 09:14 UTC, kapnobatai137 commented on coding-intro/coding-intro-core/core-concepts/programs-and-data.md
> +    [EXACT Instructions Challenge](https://youtube.com/watch?v=Ct-lOOUqmyY){website}
let's make the tag `video`

```suggestion
    [EXACT Instructions Challenge](https://youtube.com/watch?v=Ct-lOOUqmyY){video}
```

we can also say `'Exact'`. it looks better imo but it's up to you if you want to keep it as `'EXACT'`

```suggestion
    [Exact Instructions Challenge](https://youtube.com/watch?v=Ct-lOOUqmyY){video}
```

2021-03-29 09:14 UTC, kapnobatai137 commented on coding-intro/coding-intro-core/core-concepts/programs-and-data.md
> +> Check out the *Learn more* section for a realistic (and funny) example of this 🤓
```suggestion
> 💡 Check out the *Learn more* section for a realistic (and funny) example of this 🤓
```

2021-03-29 09:25 UTC, kapnobatai137 approved these changes

2021-03-29 09:30 UTC, merged