Issue 751 - Removed some occurrences of words to avoid in educational writing
enkidevs/curriculum pull request #2677
Opened 2021-04-17 02:31 UTC by PaulVaroutsos

I made some changes based on the suggestion in [Issue 751](https://github.com/enkidevs/curriculum/issues/751). Specifically the words: basically, obviously, and of course. In the places I removed or replaced these words, they were either 1. Unnecessary fluff or 2. Gave the reader a bad impression by implying the material was "obvious" or commonly known.

2021-04-17 02:31 UTC, enki-hq commented
### Insight previews:
- [ ] [enkidevs/curriculum/data-analysis/data-analysis-core/google-analytics/how-to-use-google-analytics.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/data-analysis/data-analysis-core/google-analytics/how-to-use-google-analytics.md?ref=21250638ecee3682cd6d6df6878f63b10a5ea2d4)
- [ ] [enkidevs/curriculum/java/java-fundamentals/annotations-i/variable-argument-function.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/java/java-fundamentals/annotations-i/variable-argument-function.md?ref=21250638ecee3682cd6d6df6878f63b10a5ea2d4)
- [ ] [enkidevs/curriculum/java/java-fundamentals/annotations-i/what-are-annotations.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/java/java-fundamentals/annotations-i/what-are-annotations.md?ref=21250638ecee3682cd6d6df6878f63b10a5ea2d4)
- [ ] [enkidevs/curriculum/java/java-fundamentals/iteration/implementing-the-comparable-interface-to-give-objects-a-natural-order.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/java/java-fundamentals/iteration/implementing-the-comparable-interface-to-give-objects-a-natural-order.md?ref=21250638ecee3682cd6d6df6878f63b10a5ea2d4)
- [ ] [enkidevs/curriculum/java/java-fundamentals/java-tips-iii/calling-one-constructor-from-another.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/java/java-fundamentals/java-tips-iii/calling-one-constructor-from-another.md?ref=21250638ecee3682cd6d6df6878f63b10a5ea2d4)
- [ ] [enkidevs/curriculum/java/java-fundamentals/memory/java-memory-management.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/java/java-fundamentals/memory/java-memory-management.md?ref=21250638ecee3682cd6d6df6878f63b10a5ea2d4)
- [ ] [enkidevs/curriculum/java/java-fundamentals/object-oriented-paradigm/what-is-an-object.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/java/java-fundamentals/object-oriented-paradigm/what-is-an-object.md?ref=21250638ecee3682cd6d6df6878f63b10a5ea2d4)
- [ ] [enkidevs/curriculum/java/java-fundamentals/serialization/what-is-serialization.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/java/java-fundamentals/serialization/what-is-serialization.md?ref=21250638ecee3682cd6d6df6878f63b10a5ea2d4)
- [ ] [enkidevs/curriculum/java/threading/threading/implementing-the-runnable-interface.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/java/threading/threading/implementing-the-runnable-interface.md?ref=21250638ecee3682cd6d6df6878f63b10a5ea2d4)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/iterators-generators/iterator-usages.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/iterators-generators/iterator-usages.md?ref=21250638ecee3682cd6d6df6878f63b10a5ea2d4)
- [ ] [enkidevs/curriculum/javascript/node/node-patterns/process-nexttick-callback-pattern.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/javascript/node/node-patterns/process-nexttick-callback-pattern.md?ref=21250638ecee3682cd6d6df6878f63b10a5ea2d4)
- [ ] [enkidevs/curriculum/linux/networking-and-security/ssh-remote/play-sounds-remotely.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/linux/networking-and-security/ssh-remote/play-sounds-remotely.md?ref=21250638ecee3682cd6d6df6878f63b10a5ea2d4)
- [ ] [enkidevs/curriculum/python/functional-programming/arrays-i/the-zip-built-in-function.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/arrays-i/the-zip-built-in-function.md?ref=21250638ecee3682cd6d6df6878f63b10a5ea2d4)
- [ ] [enkidevs/curriculum/python/functional-programming/functional-programming/what-is-functional-programming.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/functional-programming/what-is-functional-programming.md?ref=21250638ecee3682cd6d6df6878f63b10a5ea2d4)
- [ ] [enkidevs/curriculum/python/python-core/looping/using-else-in-loops.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/python-core/looping/using-else-in-loops.md?ref=21250638ecee3682cd6d6df6878f63b10a5ea2d4)
- [ ] [enkidevs/curriculum/python/python-core/testing/mocking-tests.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/python-core/testing/mocking-tests.md?ref=21250638ecee3682cd6d6df6878f63b10a5ea2d4)
- [ ] [enkidevs/curriculum/react/react-introduction/introduction-to-hooks/react-effect-hooks.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-introduction/introduction-to-hooks/react-effect-hooks.md?ref=21250638ecee3682cd6d6df6878f63b10a5ea2d4)
- [ ] [enkidevs/curriculum/regular-expressions/regular-expressions-introduction/even-more-practical-examples/dates.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/regular-expressions/regular-expressions-introduction/even-more-practical-examples/dates.md?ref=21250638ecee3682cd6d6df6878f63b10a5ea2d4)
- [ ] [enkidevs/curriculum/web/html/citation-elements/blockquotes.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/web/html/citation-elements/blockquotes.md?ref=21250638ecee3682cd6d6df6878f63b10a5ea2d4)
- [ ] [enkidevs/curriculum/web/html/forms-ii/radio-buttons.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/web/html/forms-ii/radio-buttons.md?ref=21250638ecee3682cd6d6df6878f63b10a5ea2d4)

2021-04-19 13:34 UTC, kapnobatai137 requested changes
Hey @PaulVaroutsos 

This is an awesome PR :tada: :tada: :tada: I only had one small comment (I think there was an extra `s` added by mistake) and after we resolve that we'll be ready to merge.

Thank you very much for taking the time to write this PR :heart:  We appreciate it a lot, and we'd like to thank you for it. If you could email me at [andrei@enki.com](mailto:andrei@enki.com) with your Enki app account username (or the email you used to register), we'd like to give you some rewards :gift:

2021-04-19 13:34 UTC, kapnobatai137 commented on regular-expressions/regular-expressions-introduction/even-more-practical-examples/dates.md
> +`/\d{4}$/`s
I think the `s` here is a typo.
```suggestion
`/\d{4}$/`
```

2021-04-20 08:17 UTC, kapnobatai137 approved these changes

2021-04-20 08:17 UTC, merged