Update what-is-your-goal.md
enkidevs/curriculum pull request #2679
Opened 2021-04-20 08:46 UTC by Stefan-Stojanovic

add deep links to SQL, Python, and Web topics

2021-04-20 08:46 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-04-20 08:47 UTC, enki-hq commented
### Insight previews:
- [ ] [enkidevs/curriculum/coding-intro/coding-intro-core/coding-intro-introduction/what-is-your-goal.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/coding-intro/coding-intro-core/coding-intro-introduction/what-is-your-goal.md?ref=f939327aefb6c21165be24b6aba9283b550a1d63)

2021-04-20 09:35 UTC, kapnobatai137 requested changes

2021-04-20 09:35 UTC, kapnobatai137 commented on coding-intro/coding-intro-core/coding-intro-introduction/what-is-your-goal.md
> +If you're interested in analyzing data you should check out our Data Analysis topic.
let's link to the data analysis topic as well
```suggestion
If you're interested in analyzing data you should check out our [Data Analysis](https://app.enki.com/skill/data-analysis) topic.
```

2021-04-20 09:35 UTC, kapnobatai137 commented on coding-intro/coding-intro-core/coding-intro-introduction/what-is-your-goal.md
> +- If you want to start by making a website, make sure you go through our [Web](https://app.enki.com/skill/web) course (which includes HTML and CSS).
Web is the topic; HTML and CSS are the courses
```suggestion
- If you want to start by making a website, make sure you go through our [Web](https://app.enki.com/skill/web) topic (which includes HTML and CSS).
```

2021-04-20 10:54 UTC, nem035 approved these changes

2021-04-20 10:54 UTC, kapnobatai137 approved these changes

2021-04-27 10:30 UTC, kapnobatai137 approved these changes

2021-04-28 15:54 UTC, kapnobatai137 approved these changes

2021-04-28 15:54 UTC, merged