[WIP] Add code-oriented questions in the first Python workout
enkidevs/curriculum pull request #2681
Opened 2021-04-21 14:28 UTC by nem035

2021-04-21 14:28 UTC, nem035 commented on python/python-core/meet-python/what-is-python.md
> +Let's write some Python code! Did you remember how to print a message?
```suggestion
Let's write some Python code! Do you remember how to print a message?
```

2021-04-21 14:28 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-04-21 14:29 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-04-21 14:29 UTC, nem035 commented on python/python-core/meet-python/what-is-python.md
> +We call these kinds of languages ??? languages.
```suggestion
We call these kinds of languages ???.
```

2021-04-21 14:29 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-04-21 15:51 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-04-21 16:12 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-04-21 16:14 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-04-21 16:16 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-04-21 16:17 UTC, nem035 commented on python/python-core/meet-python/why-learn-python.md
> +> There's no wrong answers here. The goal is to get you comfortable with reading code :)
```suggestion
> There're no wrong answers here. The goal is to get you comfortable with reading code :)
```

2021-04-21 16:17 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-04-22 09:11 UTC, kapnobatai137 requested changes
looks good :+1: I've left some copy improvement suggestions

2021-04-22 09:11 UTC, kapnobatai137 commented on python/python-core/meet-python/what-is-python.md
> +Python is a programming language that can be used for just about anything.
let's switch to the active voice here
```suggestion
Python is a programming language that you can use for just about anything.
```

2021-04-22 09:11 UTC, kapnobatai137 commented on python/python-core/meet-python/what-is-python.md
> +Just like how English has special types of words like *verb* and *nouns*, as well as rules on which should come first to make a valid sentence, Python has a different set of rules on how to make vali
we should remove the "Just like" at the start of the sentence. how does this sound?
```suggestion
The English language has unique types of words like *verb* and *nouns* and rules on which should come first to make a correct sentence; Python has a different set of rules on making valid Python statements.
```

2021-04-22 09:11 UTC, kapnobatai137 commented on python/python-core/meet-python/why-learn-python.md
> +Python is also concise and usually requires less code for the same task than languages such as Java or C++.
let's replace "such as" with "like". I've also added "other" here to keep the same message
```suggestion
Python is also concise and usually requires less code for the same task than other languages like Java or C++.
```

2021-04-22 09:11 UTC, kapnobatai137 commented on python/python-core/meet-python/why-learn-python.md
> +Python is known as an easy-to-read language due to its close similarity to English.
I think it's safe to remove "known as" here
```suggestion
Python is an easy-to-read language due to its close similarity to English.
```

2021-04-22 09:16 UTC, enki-hq commented
### Insight previews:
- [ ] [enkidevs/curriculum/python/python-core/meet-python/python-hello-world.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-core/meet-python/python-hello-world.md?ref=509ec0eb56065db054b1d6d68810fe6ab2fa6746)
- [ ] [enkidevs/curriculum/python/python-core/meet-python/python-versions.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-core/meet-python/python-versions.md?ref=509ec0eb56065db054b1d6d68810fe6ab2fa6746)
- [ ] [enkidevs/curriculum/python/python-core/meet-python/what-is-python.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-core/meet-python/what-is-python.md?ref=509ec0eb56065db054b1d6d68810fe6ab2fa6746)
- [ ] [enkidevs/curriculum/python/python-core/meet-python/why-learn-python.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-core/meet-python/why-learn-python.md?ref=509ec0eb56065db054b1d6d68810fe6ab2fa6746)

2021-04-23 12:46 UTC, kapnobatai137 submitted a review, later dismissed

2021-05-04 11:00 UTC, kapnobatai137 approved these changes

2021-05-04 11:00 UTC, merged