Update checkbox-groups.md
enkidevs/curriculum pull request #2691
Opened 2021-05-04 07:01 UTC by Stefan-Stojanovic

Move link to the `links` section as opposed to an HTML comment at the bottom of the page

2021-05-04 07:02 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-05-04 07:02 UTC, enki-hq commented
### Insight previews:
- [ ] [enkidevs/curriculum/web/html/forms-ii/checkbox-groups.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/forms-ii/checkbox-groups.md?ref=1d3686ddd3d08f6f268cf0b399b6022013f0f816)

2021-05-04 10:09 UTC, kapnobatai137 requested changes
looks good :ok_hand: I only had one comment regarding the copy

2021-05-05 10:16 UTC, kapnobatai137 approved these changes

2021-05-05 10:17 UTC, merged