Update converting-to-and-from-json.md
enkidevs/curriculum pull request #2743
Opened 2021-06-14 13:40 UTC by Stefan-Stojanovic

remove arrow function as it wasn't taught yet

2021-06-14 13:40 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-06-14 13:42 UTC, enki-hq commented
### Insight previews:
- [ ] [enkidevs/curriculum/javascript/javascript-core/objects/converting-to-and-from-json.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/objects/converting-to-and-from-json.md?ref=db97b6e0a26f221c30ff01a7c9fed048d5de356d)

2021-06-15 14:14 UTC, kapnobatai137 requested changes

2021-06-15 14:14 UTC, kapnobatai137 commented on javascript/javascript-core/objects/converting-to-and-from-json.md
> +    toJSON(){ return {food: 'dog snacks'}}
I think we can format this nicely
```suggestion
    toJSON() {
      return {
        food: 'dog snacks'
      };
    }
```

2021-06-15 14:31 UTC, kapnobatai137 approved these changes

2021-06-15 14:31 UTC, merged