Update manipulating-shapes-using-css-clip-path.md
enkidevs/curriculum pull request #2753
Opened 2021-06-22 14:28 UTC by Stefan-Stojanovic

2021-06-22 14:29 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-06-22 14:29 UTC, enki-hq commented
### Insight previews:
- [ ] [enkidevs/curriculum/web/styling/css-animation/manipulating-shapes-using-css-clip-path.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/styling/css-animation/manipulating-shapes-using-css-clip-path.md?ref=4941bf4eedd39191e87591aa108e8566c7c4b499)

2021-06-23 14:10 UTC, kapnobatai137 requested changes

2021-06-23 14:10 UTC, kapnobatai137 commented on web/styling/css-animation/manipulating-shapes-using-css-clip-path.md
>  **Note:** Top-left corner of the `element` is located at *(0%,0%)*, while the bottom-right one at *(100%, 100%)*.
```suggestion
> 💡 Top-left corner of the `element` is located at `(0%,0%)`, while the bottom-right one at `(100%, 100%)`.
```

2021-06-23 14:10 UTC, kapnobatai137 commented on web/styling/css-animation/manipulating-shapes-using-css-clip-path.md
> +Here is the HTML code that contains the links to them. The first one is just the image. The second one is the same image but with a class:
let's shorten this phrase a bit
```suggestion
Here's the HTML code:
```

2021-06-23 14:10 UTC, kapnobatai137 commented on web/styling/css-animation/manipulating-shapes-using-css-clip-path.md
> +Without any CSS the images are identical. However, if we add some CSS to the `clipped` class:
we can shorten this a bit too
```suggestion
Let's see what happens when we use `ellipse` instead of `polygon`:
```

2021-06-23 14:10 UTC, kapnobatai137 commented on web/styling/css-animation/manipulating-shapes-using-css-clip-path.md
> +![enki-image-output-for-manipulating-shapes](https://img.enkipro.com/a50732d668d8f66212f89a8420942551.png)
imo it's fine if we just show the result under the code block
```suggestion
![enki-image-output-for-manipulating-shapes](https://img.enkipro.com/a50732d668d8f66212f89a8420942551.png)
```

2021-06-23 15:29 UTC, kapnobatai137 approved these changes

2021-06-23 15:49 UTC, merged