add "how to create empty dictionaries" to the "The Dictionary Insight"
enkidevs/curriculum pull request #2829
Opened 2021-08-12 10:14 UTC by Stefan-Stojanovic

2021-08-12 10:14 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-08-12 10:15 UTC, enki-hq commented
### Insight previews:
- [ ] [enkidevs/curriculum/python/python-core/unordered-data-types/dictionary-standard-mapping-type.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-core/unordered-data-types/dictionary-standard-mapping-type.md?ref=4be07047a2297aede26ca2b7f1ecb14abd9c1e05)

2021-08-12 14:33 UTC, Loopiezlol submitted a review, later dismissed
This looks great, but I would also add a mention in [this](https://app.enkipro.com/public/insight/5eb1862ba341dc051185ec0a) insight right at the end, showing that an empty dictionary could also be used to generate dicts from keys

2021-08-15 15:37 UTC, nem035 commented on python/python-core/unordered-data-types/dictionary-methods-ii.md
> +If we update tha `famous_siblings` example, we would get the same result:
```suggestion
If we update the `famous_siblings` example, we would get the same result:
```

2021-08-16 15:49 UTC, nem035 approved these changes

2021-08-17 14:53 UTC, kapnobatai137 requested changes
@Stefan-Stojanovic looks good! we need to fix two typos and then it's safe to merge

2021-08-17 14:53 UTC, kapnobatai137 commented on python/python-core/unordered-data-types/dictionary-standard-mapping-type.md
> +Here's how you can create an empty dicitonary:
```suggestion
Here's how you can create an empty dictionary:
```

2021-08-17 14:53 UTC, kapnobatai137 commented on python/python-core/unordered-data-types/dictionary-standard-mapping-type.md
> +Here is a sample of a pupulated dictionary:
```suggestion
Here is an example of a populated dictionary:
```

2021-08-18 10:26 UTC, kapnobatai137 approved these changes
@Stefan-Stojanovic nice, let's get this live :rocket:

2021-08-18 11:17 UTC, merged