Update speed-up-your-for-loop-using-map-or-list-comprehensions.md
enkidevs/curriculum pull request #2853
Opened 2021-08-22 11:33 UTC by Stefan-Stojanovic

Update variables to snake_case and update the PQ to use list comprehension as it is the recommended pythonic way

The output of :
```python
input_list = ['A', 'E', 'I', 'o', 'u']
lower_list = map(str.lower, input_list)
print(lower_list)
```
Looks like this:
```plain-text
<map object at 0x7f3d57a3f700>
```
Whereas the output of:
```python
input_list = ['A', 'E', 'I', 'o', 'u']

lower_list = [word.upper() \
  for word in input_list]
print(lower_list)
```
Looks like this:
```plain-text
['A', 'E', 'I', 'O', 'U']
```
So I changed the question to use list comprehension instead of map (we also recommend this)

2021-08-22 11:33 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-08-22 11:35 UTC, enki-hq commented
### Insight previews:
- [ ] [enkidevs/curriculum/python/functional-programming/comprehension/speed-up-your-for-loop-using-map-or-list-comprehensions.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/comprehension/speed-up-your-for-loop-using-map-or-list-comprehensions.md?ref=d75e721c05ba8458c57ffba28530d9ea4e873402)

2021-08-23 08:50 UTC, kapnobatai137 requested changes

2021-08-23 08:50 UTC, kapnobatai137 commented on python/functional-programming/comprehension/speed-up-your-for-loop-using-map-or-list-comprehensions.md
> +for word in input_listt:
small typo
```suggestion
for word in input_list:
```

2021-08-25 09:54 UTC, kapnobatai137 approved these changes

2021-08-25 10:11 UTC, merged