Update collections-discussion-insight.md
enkidevs/curriculum pull request #2882
Opened 2021-09-01 17:00 UTC by Stefan-Stojanovic

2021-09-01 17:00 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2021-09-01 17:01 UTC, enki-hq commented
### Insight previews:
- [ ] [enkidevs/curriculum/coding-intro/coding-intro-core/collections/collections-discussion-insight.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/coding-intro/coding-intro-core/collections/collections-discussion-insight.md?ref=7960368f4eca1b9dd4ad84ffcbeeef509285d53f)

2021-09-07 09:35 UTC, kapnobatai137 requested changes

2021-09-07 09:35 UTC, kapnobatai137 commented on coding-intro/coding-intro-core/collections/collections-discussion-insight.md
>      # Then, use the print() function to display one of the collection's elements
```suggestion
    # Then, use the print() function to display one of the list's elements
```

2021-09-07 09:37 UTC, kapnobatai137 approved these changes
:rocket:

2021-09-07 09:37 UTC, merged