Update anchor-links.md
enkidevs/curriculum pull request #3041
Opened 2022-02-14 13:18 UTC by Stefan-Stojanovic

2022-02-14 13:18 UTC, enki-hq commented
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

2022-02-14 13:19 UTC, enki-hq commented
### Insight previews:
- [ ] [enkidevs/curriculum/web/html/links/anchor-links.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/links/anchor-links.md?ref=c86c3a1aa2f80fcafae7be6ca3a682d6797af6c8)

2022-02-14 13:25 UTC, kapnobatai137 requested changes

2022-02-14 13:25 UTC, kapnobatai137 commented on CHANGELOG.md
> +-[Web - Anchor Links - Make RQ clearer](https://github.com/enkidevs/curriculum/pull/3041)
```suggestion
- [Web - Anchor Links - Make RQ clearer](https://github.com/enkidevs/curriculum/pull/3041) 
```

2022-02-14 13:25 UTC, kapnobatai137 commented on web/html/links/anchor-links.md
> +Add the missing code to create an anchor link that navigates to the portion of the page whose id is `contact`:
what do you think about this?

```suggestion
Create an anchor link that navigates to the HTML element with the `contact` id:
```

2022-02-15 09:46 UTC, Stefan-Stojanovic commented on CHANGELOG.md
> +-[Web - Anchor Links - Make RQ clearer](https://github.com/enkidevs/curriculum/pull/3041)
👍

2022-02-15 09:46 UTC, Stefan-Stojanovic commented on web/html/links/anchor-links.md
> +Add the missing code to create an anchor link that navigates to the portion of the page whose id is `contact`:
Sounds good

2022-02-15 09:50 UTC, kapnobatai137 submitted a review, later dismissed

2022-02-15 10:07 UTC, merged