Clarification to question
enkidevs/curriculum pull request #3056
Opened 2022-03-13 20:57 UTC by rettal

Previous question is/was missing vital information for the question to make sense.

2022-03-13 20:58 UTC, enki-hq commented
### Insight previews:
- [ ] [enkidevs/curriculum/sql/dql/aggregate-queries/distinct-clause.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/sql/dql/aggregate-queries/distinct-clause.md?ref=9c4f069279e93df5b3b67a3b31609c05ba4a8662)

2022-03-14 08:41 UTC, kapnobatai137 requested changes

2022-03-14 08:41 UTC, kapnobatai137 commented on sql/dql/aggregate-queries/distinct-clause.md
> +Consider the following table named GRADES with the following query. Fill the gaps such that we will have no duplicate NAME's in the resulting table:
Hey @rettal,

Thanks for taking the time to improve this question!

I have a couple of minor suggestions:
- we should enclose the table & column names in backticks
- we should remove the possessive (NAME's) & change it to plural (NAMEs)

```suggestion
Consider the following table named `GRADES` with the following query. Fill the gaps such that we will have no duplicate `NAME`s in the resulting table:
```

2022-03-15 08:58 UTC, kapnobatai137 approved these changes
Thank you for the contribution @rettal!

2022-03-15 08:58 UTC, merged